<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="1.4.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HttpDancer.Core\HttpDancer.Core.csproj" />
      <ProjectReference Include="..\HttpDancer.Html\HttpDancer.Html.csproj" />
      <ProjectReference Include="..\HttpDancer.Utilities\HttpDancer.Utilities.csproj" />
    </ItemGroup>

</Project>
