@baseUrl = https://digst.dk
@rate = 10
@rateWindow = 00:00:01

HEAD /it-loesninger/
HEAD /it-loesninger/altid/
HEAD /it-loesninger/altid/til-virksomheder/
HEAD /it-loesninger/altid/til-myndigheder/
HEAD /it-loesninger/altid/teknisk-vejledning/
HEAD /it-loesninger/borgerdk/
HEAD /it-loesninger/borgerdk/om-loesningen/
HEAD /it-loesninger/borgerdk/om-loesningen/borgerdk-baggrund-og-historie/
HEAD /it-loesninger/borgerdk/om-loesningen/er-du-journalist/
HEAD /it-loesninger/borgerdk/om-loesningen/borgerdk-et-faellesoffentligt-samarbejde/
HEAD /it-loesninger/borgerdk/om-loesningen/tal-og-statistik-om-borgerdk/
HEAD /it-loesninger/borgerdk/den-gode-brugeroplevelse-er-omdrejningspunktet/
HEAD /it-loesninger/borgerdk/produkter-for-myndigheder/
HEAD /it-loesninger/borgerdk/mit-overblik/
HEAD /it-loesninger/borgerdk/mit-overblik/om-mit-overblik-paa-borgerdk/
HEAD /it-loesninger/borgerdk/mit-overblik/infrastrukturen-bag-mit-overblik/
HEAD /it-loesninger/digital-fuldmagt/
HEAD /it-loesninger/digital-fuldmagt/om-loesningen/
HEAD /it-loesninger/digital-fuldmagt/anvendelse/
HEAD /it-loesninger/digital-fuldmagt/vejledninger/
HEAD /it-loesninger/digital-fuldmagt/support/
HEAD /it-loesninger/digital-post/
HEAD /it-loesninger/digital-post/om-loesningen/
HEAD /it-loesninger/digital-post/om-loesningen/baggrund/
HEAD /it-loesninger/digital-post/om-loesningen/platforme/
HEAD /it-loesninger/digital-post/om-loesningen/leverandoerer/
HEAD /it-loesninger/digital-post/om-loesningen/besked-om-ny-post/
HEAD /it-loesninger/digital-post/om-loesningen/tal-og-statistik/
HEAD /it-loesninger/digital-post/lovgivning/
HEAD /it-loesninger/digital-post/anvendelse-for-offentlige-myndigheder/
HEAD /it-loesninger/digital-post/anvendelse-for-offentlige-myndigheder/bliv-offentlig-afsender/
HEAD /it-loesninger/digital-post/anvendelse-for-offentlige-myndigheder/driftsinformation-og-fejlrapportering/
HEAD /it-loesninger/digital-post/anvendelse-for-offentlige-myndigheder/rettighedsstyring/
HEAD /it-loesninger/digital-post/anvendelse-for-offentlige-myndigheder/afsender-og-modtagersystemer/
HEAD /it-loesninger/digital-post/anvendelse-for-offentlige-myndigheder/kontaktstruktur/
HEAD /it-loesninger/digital-post/hjaelpeunivers-send-bedre-digital-post/
HEAD /it-loesninger/digital-post/hjaelpeunivers-send-bedre-digital-post/kom-godt-i-gang-med-memo/
HEAD /it-loesninger/digital-post/hjaelpeunivers-send-bedre-digital-post/visuelle-eksempler/case-om-aftale/
HEAD /it-loesninger/digital-post/hjaelpeunivers-send-bedre-digital-post/visuelle-eksempler/case-med-betaling/
HEAD /it-loesninger/digital-post/hjaelpeunivers-send-bedre-digital-post/visuelle-eksempler/case-med-svarfrist/
HEAD /it-loesninger/digital-post/hjaelpeunivers-send-bedre-digital-post/visuelle-eksempler/case-med-selvbetjening/
HEAD /it-loesninger/digital-post/hjaelpeunivers-send-bedre-digital-post/teknikerens-vaerktoejskasse/
HEAD /it-loesninger/digital-post/vejledninger-og-begivenheder/
HEAD /it-loesninger/digital-post/vejledninger-og-begivenheder/afholdte-webinarer/
HEAD /it-loesninger/digital-post/vejledninger-og-begivenheder/tilmelding-til-begivenheder/
HEAD /it-loesninger/digital-post/vejledninger-og-begivenheder/tilmelding-til-begivenheder/om-databehandling/
HEAD /it-loesninger/digital-post/kommunikation/
HEAD /it-loesninger/digital-post/kommunikation/arabisk/
HEAD /it-loesninger/digital-post/kommunikation/engelsk/
HEAD /it-loesninger/digital-post/kommunikation/farsi/
HEAD /it-loesninger/digital-post/kommunikation/polsk/
HEAD /it-loesninger/digital-post/kommunikation/somali/
HEAD /it-loesninger/digital-post/kommunikation/tegnsprog-dansk/
HEAD /it-loesninger/digital-post/kommunikation/tyrkisk/
HEAD /it-loesninger/digital-post/kommunikation/ukrainsk/
HEAD /it-loesninger/digital-post/support/
HEAD /it-loesninger/digital-post/tilsyn/
HEAD /it-loesninger/digital-post/bliv-visningsklient/
HEAD /it-loesninger/digital-post/netvaerk-om-digital-post/
HEAD /it-loesninger/digitalt-samtykke/
HEAD /it-loesninger/digitalt-samtykke/om-loesning/
HEAD /it-loesninger/digitalt-samtykke/support-til-digitalt-samtykke/
HEAD /it-loesninger/digitalt-samtykke/tilslutning-til-digitalt-samtykke/
HEAD /it-loesninger/digitaliserdk/
HEAD /it-loesninger/digitaliserdk/om-loesningen/
HEAD /it-loesninger/digitaliserdk/anvendelse/
HEAD /it-loesninger/eid-og-single-digital-gateway/
HEAD /it-loesninger/eid-og-single-digital-gateway/eu-forordninger-vedroerende-eid/
HEAD /it-loesninger/eid-og-single-digital-gateway/brug-af-eid-i-offentlige-digitale-loesninger-paa-tvaers-af-eueoes/
HEAD /it-loesninger/eid-og-single-digital-gateway/tilslutning-til-eid-gateway/
HEAD /it-loesninger/eid-og-single-digital-gateway/single-digital-gateway/
HEAD /it-loesninger/eid-og-single-digital-gateway/vejledninger-til-myndigheder-om-sdg-forordningen/
HEAD /it-loesninger/eid-og-single-digital-gateway/eidas2-og-den-digitale-identitetstegnebog/
HEAD /it-loesninger/faellesoffentligt-testdatasaet/
HEAD /it-loesninger/koerekort-app/
HEAD /it-loesninger/koerekort-app/om-loesningen/
HEAD /it-loesninger/koerekort-app/spoergsmaal-og-svar/
HEAD /it-loesninger/koerekort-app/support/
HEAD /it-loesninger/koerekort-app/vejledninger/
HEAD /it-loesninger/koerekort-app/privatlivspolitik/
HEAD /it-loesninger/koerekort-app/tilgaengelighedserklaering-for-koerekort-app/
HEAD /it-loesninger/mitid/
HEAD /it-loesninger/mitid/om-mitid/
HEAD /it-loesninger/mitid/om-mitid/tal-og-statistik/
HEAD /it-loesninger/mitid/nyheder-om-mitid/
HEAD /it-loesninger/mitid/nyheder-om-mitid/nyheder-fra-2022/mitid-brev-sendt-til-for-mange-modtagere-ved-en-fejl/
HEAD /it-loesninger/mitid/nyheder-om-mitid/nyheder-fra-2022/nu-skal-du-ogsaa-bruge-mitid-naar-du-handler-paa-nettet/
HEAD /it-loesninger/mitid/nyheder-om-mitid/nyheder-fra-2022/om-nemid-og-mitid-efter-d-31-oktober/
HEAD /it-loesninger/mitid/nyheder-om-mitid/nyheder-fra-2021/mitid-en-sikker-loesning/
HEAD /it-loesninger/mitid/nyheder-om-mitid/nyheder-fra-2021/har-du-faaet-mitid-husk-at-beholde-dit-nemid/
HEAD /it-loesninger/mitid/nyheder-om-mitid/nyheder-fra-2021/12-brokere-i-mitid/
HEAD /it-loesninger/mitid/lovgivning/
HEAD /it-loesninger/mitid/support/
HEAD /it-loesninger/mitid/til-brokere/liste-over-godkendte-brokere/
HEAD /it-loesninger/mitid/forgaengeren-til-mitid/
HEAD /it-loesninger/mitid-erhverv/
HEAD /it-loesninger/nemkonto/
HEAD /it-loesninger/nemkonto/lovgivning/
HEAD /it-loesninger/nemkonto/om-loesningen/
HEAD /it-loesninger/nemkonto/nemkonto-for-sagsbehandlere/
HEAD /it-loesninger/nemkonto/udbud-af-et-nyt-nemkonto-system/
HEAD /it-loesninger/nemkonto/support/
HEAD /it-loesninger/nemkonto/kompensation-ved-svindel-med-nemkonto/
HEAD /it-loesninger/nemkonto/kompensation-ved-svindel-med-nemkonto/ikke-digitale-ansoegningsforloeb/
HEAD /it-loesninger/nemkonto/kompensation-ved-svindel-med-nemkonto/behandling-af-persondata/
HEAD /it-loesninger/nemlog-in/
HEAD /it-loesninger/nemlog-in/om-loesningen/
HEAD /it-loesninger/nemlog-in/om-loesningen/komponenter-og-standarder-i-nemlog-in/
HEAD /it-loesninger/nemlog-in/om-loesningen/persondata/
HEAD /it-loesninger/nemlog-in/udbud-af-nemlog-in/
HEAD /it-loesninger/nemlog-in/udbud-af-nemlog-in/markedsdialog-om-udbud-af-nemlog-in-loesningen-vinter-2025/
HEAD /it-loesninger/nemlog-in/udbud-af-nemlog-in/markedsdialog-om-tillidstjenester-vinter-2025/
HEAD /it-loesninger/nemlog-in/udbud-af-nemlog-in/markedsdialog-om-udbud-af-nemlog-in-efteraar-2025/
HEAD /it-loesninger/nemlog-in/udbud-af-nemlog-in/markedsdialog-om-udbud-af-nemlog-in-foraar-2025/
HEAD /it-loesninger/nemlog-in/udbud-af-nemlog-in/informationsmoede-den-1-december-2025/
HEAD /it-loesninger/nemlog-in/nyt-design-i-nemlog-in/
HEAD /it-loesninger/nemsms/
HEAD /it-loesninger/nemsms/om-loesningen/
HEAD /it-loesninger/nemsms/om-loesningen/tal-og-statistik/
HEAD /it-loesninger/nemsms/anvendelse/
HEAD /it-loesninger/nemsms/support/
HEAD /it-loesninger/orkestreringskomponenten/
HEAD /it-loesninger/orkestreringskomponenten/om-orkestreringskomponenten/
HEAD /it-loesninger/orkestreringskomponenten/standardisering/
HEAD /it-loesninger/standarder/
HEAD /it-loesninger/standarder/nsis/
HEAD /it-loesninger/standarder/nsis/ofte-stillede-spoergsmaal-om-nsis/
HEAD /it-loesninger/standarder/oiosaml-profiler/
HEAD /it-loesninger/standarder/oiosaml-profiler/aeldre-versioner-af-oiosaml-profiler/
HEAD /it-loesninger/standarder/openid-connect-profiler/
HEAD /it-loesninger/standarder/oio-identity-based-web-services-oio-idws/
HEAD /it-loesninger/standarder/oio-identity-based-web-services-oio-idws/oio-identity-based-web-services-11-tidligere-version/
HEAD /it-loesninger/standardkontrakter/
HEAD /it-loesninger/standardkontrakter/k01-standardkontrakt-for-kortvarige-it-projekter/
HEAD /it-loesninger/standardkontrakter/k02-standardkontrakt-for-laengerevarende-it-projekter/
HEAD /it-loesninger/standardkontrakter/k03-standardkontrakt-for-agile-it-projekter/
HEAD /it-loesninger/standardkontrakter/k04-standardkontrakt-for-it-drift/
HEAD /it-loesninger/standardkontrakter/standardklausuler-for-it-drift/
HEAD /it-loesninger/standardkontrakter/standardklausuler-for-it-drift/fast-track-resolution-hurtig-afgoerelse/
HEAD /it-loesninger/standardkontrakter/standardklausuler-for-it-drift/fix-first-settle-later/
HEAD /it-loesninger/standardkontrakter/standardklausuler-for-it-drift/ophoer/
HEAD /it-loesninger/standardkontrakter/standardklausuler-for-it-drift/prisregulering/
HEAD /it-loesninger/standardkontrakter/standardklausuler-for-it-drift/samarbejde-og-samarbejdsorganisation/
HEAD /it-loesninger/sundhedskort-app/
HEAD /it-loesninger/sundhedskort-app/om-loesningen/
HEAD /it-loesninger/sundhedskort-app/spoergsmaal-og-svar/
HEAD /it-loesninger/sundhedskort-app/support/
HEAD /it-loesninger/sundhedskort-app/vejledninger/
HEAD /it-loesninger/sundhedskort-app/tilgaengelighedserklaering-for-sundhedskort-app/
HEAD /it-loesninger/sundhedskort-app/privatlivspolitik/
HEAD /it-loesninger/servicedeklaration/
HEAD /it-loesninger/support-til-it-loesninger/
HEAD /sikkerhed/cybersikkerhedspagten/cybersikkerhedspagtens-arbejde/
HEAD /sikkerhed/cybersikkerhedspagten/medlemmer-i-cybersikkerhedspagten/
HEAD /sikkerhed/cybersikkerhedspagten/bliv-associeret-medlem-af-pagten/
HEAD /data/
HEAD /data/it-arkitektur/
HEAD /data/it-arkitektur/udvalget-for-arkitektur-og-standarder/
HEAD /data/it-arkitektur/de-faelles-principper-for-offentlig-digitalisering/
HEAD /data/it-arkitektur/arkitektur-og-modelreviews/
HEAD /data/it-arkitektur/arkitektur-og-modelreviews/tjekliste-til-arkitekturreview/
HEAD /data/it-arkitektur/arkitektur-og-modelreviews/tjekliste-til-modelreview/
HEAD /data/it-arkitektur/raadgivning-om-arkitektur-og-datamodellering/
HEAD /data/it-arkitektur/netvaerk-for-digital-arkitektur/
HEAD /data/datavejviser/
HEAD /data/videreanvendelse-af-offentlige-data/
HEAD /data/videreanvendelse-af-offentlige-data/psi-loven-og-ikke-beskyttede-data/
HEAD /data/videreanvendelse-af-offentlige-data/betaling-for-data/
HEAD /data/videreanvendelse-af-offentlige-data/licens-og-brugsvilkaar-for-offentlige-data/
HEAD /data/datastyringsforordningen-og-beskyttede-data/
HEAD /data/dansk-sprogteknologi/
HEAD /data/dansk-sprogteknologi/pilotprojekt-om-byraads-og-udvalgsdata/
HEAD /data/vejledning-til-anvendelse-af-cloudservices/
HEAD /data/det-offentlige-danmark/
HEAD /data/det-offentlige-danmark/publikationer/
HEAD /data/dataetik-i-virksomheder/
HEAD /data/dataetik-i-virksomheder/guide-til-virksomheder-dataetik-i-anvendelsen-af-tredjepartstjenester/
HEAD /kunstig-intelligens/
HEAD /kunstig-intelligens/guides-til-brug-af-kunstig-intelligens/
HEAD /kunstig-intelligens/guides-til-brug-af-kunstig-intelligens/guide-til-borgere/
HEAD /kunstig-intelligens/guides-til-brug-af-kunstig-intelligens/guide-til-virksomheder/
HEAD /kunstig-intelligens/guides-til-brug-af-kunstig-intelligens/guide-offentlige-myndigheder/
HEAD /kunstig-intelligens/strategier-for-kunstig-intelligens/
HEAD /kunstig-intelligens/signaturprojekter/
HEAD /kunstig-intelligens/signaturprojekter/signaturprojekternes-erfaringer/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/gode-raad-til-at-komme-i-gang-med-generativ-kunstig-intelligens/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/borgere-i-esbjerg-kan-chatte-med-kommunen-paa-op-til-90-sprog/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/rigshospitalets-chatbot-besvarer-patienters-spoergsmaal/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/generativ-kunstig-intelligens-hjaelper-roskilde-med-referater-af-hoeringssvar/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/atp-bruger-generativ-kunstig-intelligens-til-at-skrive-journalnotater/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/generativ-kunstig-intelligens-analyserer-store-maengder-data-fra-virksomheders-aarsrapporter/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/medarbejderne-i-vejle-har-generativ-kunstig-intelligens-lige-ved-haanden/
HEAD /kunstig-intelligens/inspirationskatalog-til-generativ-kunstig-intelligens/miljoestyrelsen-ruster-organisationen-til-generativ-kunstig-intelligens/
HEAD /kunstig-intelligens/virksomheders-afproevning-af-ai-baserede-produkter/
HEAD /kunstig-intelligens/kommunikation-paa-borgerdk-med-generativ-ai-assistent/
HEAD /kunstig-intelligens/casekatalog-ai-loesninger-med-dokumenteret-effekt/
HEAD /kunstig-intelligens/casekatalog-ai-loesninger-med-dokumenteret-effekt/naestved-kommune-reducerer-faldulykker-ved-at-implementere-ai-teknologi-paa-plejehjem/
HEAD /kunstig-intelligens/casekatalog-ai-loesninger-med-dokumenteret-effekt/region-hovedstaden-optimerer-mammografiscreeninger-med-ai/
HEAD /kunstig-intelligens/casekatalog-ai-loesninger-med-dokumenteret-effekt/skatteforvaltningen-bruger-kunstig-intelligens-til-at-fordele-skriftlige-henvendelser/
HEAD /kunstig-intelligens/casekatalog-ai-loesninger-med-dokumenteret-effekt/atp-kombinerer-dataflow-med-ai-og-goer-det-komplekse-enkelt-for-borgerne/
HEAD /kunstig-intelligens/casekatalog-ai-loesninger-med-dokumenteret-effekt/faxe-kommune-forbedrer-veje-og-trafiksikkerhed-med-ai-loesning/
HEAD /kunstig-intelligens/casekatalog-ai-loesninger-med-dokumenteret-effekt/cames-rigshospitalet-prenaital-kan-sikre-bedre-diagnostik-af-gravide-med-ai/
HEAD /kunstig-intelligens/danske-virksomheders-anvendelse-af-ai/
HEAD /digital-inklusion/
HEAD /digital-inklusion/viden-om-digital-inklusion/
HEAD /digital-inklusion/viden-om-digital-inklusion/hvem-oplever-udfordringer-ved-det-digitale/
HEAD /digital-inklusion/viden-om-digital-inklusion/analyse-om-digital-inklusion/
HEAD /digital-inklusion/viden-om-digital-inklusion/borgernes-moede-med-fuldmagter/
HEAD /digital-inklusion/viden-om-digital-inklusion/konference-om-digital-inklusion-2024/
HEAD /digital-inklusion/principper-for-digital-inklusion/
HEAD /digital-inklusion/principper-for-digital-inklusion/halvdagworkshop-om-principper-for-digital-inklusion/
HEAD /digital-inklusion/principper-for-digital-inklusion/halvdagworkshop-om-principper-for-digital-inklusion/materiale-til-workshop-om-principper-for-digital-inklusion/
HEAD /digital-inklusion/principper-for-digital-inklusion/halvdagworkshop-om-principper-for-digital-inklusion/spoergsmaal-og-svar/
HEAD /digital-inklusion/principper-for-digital-inklusion/halvdagworkshop-om-principper-for-digital-inklusion/case-fra-koebenhavns-kommune/
HEAD /digital-inklusion/principper-for-digital-inklusion/hav-oeje-for-digitaliseringens-konsekvenser/
HEAD /digital-inklusion/principper-for-digital-inklusion/hav-oeje-for-digitaliseringens-konsekvenser/vaerktoej-inklusionspersonaer/
HEAD /digital-inklusion/principper-for-digital-inklusion/hav-oeje-for-digitaliseringens-konsekvenser/case-fra-rejsekort-rejseplan/
HEAD /digital-inklusion/principper-for-digital-inklusion/hav-oeje-for-digitaliseringens-konsekvenser/case-fra-aarhus-kommune/
HEAD /digital-inklusion/principper-for-digital-inklusion/design-loesninger-for-alle/
HEAD /digital-inklusion/principper-for-digital-inklusion/design-loesninger-for-alle/vaerktoej-det-faelles-designsystem/
HEAD /digital-inklusion/principper-for-digital-inklusion/design-loesninger-for-alle/vaerktoej-kls-servicedesignvaerktoej/
HEAD /digital-inklusion/principper-for-digital-inklusion/design-loesninger-for-alle/case-fra-udviklings-og-forenklingsstyrelsen/
HEAD /digital-inklusion/principper-for-digital-inklusion/design-loesninger-for-alle/vaerktoej-metodebank/
HEAD /digital-inklusion/principper-for-digital-inklusion/design-loesninger-for-alle/vaerktoej-brugervenlighedstest/
HEAD /digital-inklusion/principper-for-digital-inklusion/design-loesninger-for-alle/vaerktoej-guide-til-gode-brugeroplevelser/
HEAD /digital-inklusion/principper-for-digital-inklusion/kommuniker-saa-alle-forstaar-det/
HEAD /digital-inklusion/principper-for-digital-inklusion/kommuniker-saa-alle-forstaar-det/vaerktoej-paaroerendesprog/
HEAD /digital-inklusion/principper-for-digital-inklusion/kommuniker-saa-alle-forstaar-det/case-fra-skattestyrelsen/
HEAD /digital-inklusion/principper-for-digital-inklusion/kommuniker-saa-alle-forstaar-det/case-fra-region-h/
HEAD /digital-inklusion/principper-for-digital-inklusion/hjaelp-borgerne-med-deres-digitale-goeremaal/
HEAD /digital-inklusion/principper-for-digital-inklusion/hjaelp-borgerne-med-deres-digitale-goeremaal/case-fra-digitaliseringsstyrelsen/
HEAD /digital-inklusion/principper-for-digital-inklusion/hjaelp-dem-der-hjaelper/case-fra-region-h-psykiatri/
HEAD /digital-inklusion/principper-for-digital-inklusion/hjaelp-dem-der-hjaelper/vaerktoej-laese-og-skriveadgang/
HEAD /digital-inklusion/principper-for-digital-inklusion/stil-anvendelige-alternativer-til-raadighed/
HEAD /digital-inklusion/principper-for-digital-inklusion/stil-anvendelige-alternativer-til-raadighed/case-fra-roskilde-kommune/
HEAD /digital-inklusion/inklusionsnetvaerk/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/medlemmer/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/netvaerksmoeder/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/netvaerksmoeder/21-oktober-2025/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/netvaerksmoeder/25-marts-2025/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/netvaerksmoeder/4-december-2024/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/netvaerksmoeder/10-april-2024/
HEAD /digital-inklusion/inklusionsnetvaerk/netvaerk-for-digital-inklusion/netvaerksmoeder/26-oktober-2023/
HEAD /digital-inklusion/inklusionsnetvaerk/myndighedsnetvaerk-for-digital-inklusion/
HEAD /digital-inklusion/inklusionsnetvaerk/myndighedsnetvaerk-for-digital-inklusion/netvaerksmoeder/
HEAD /digital-inklusion/inklusionsnetvaerk/myndighedsnetvaerk-for-digital-inklusion/netvaerksmoeder/program-for-6-moede-i-myndighedsnetvaerket/
HEAD /digital-inklusion/inklusionsnetvaerk/myndighedsnetvaerk-for-digital-inklusion/netvaerksmoeder/referat-af-6-moede/
HEAD /digital-inklusion/pulje-til-frivilligindsatser/
HEAD /digital-inklusion/pulje-til-frivilligindsatser/tilskudspuljens-formaal/
HEAD /digital-inklusion/pulje-til-frivilligindsatser/projekter-der-har-faaet-tildelt-midler-i-foerste-runde/
HEAD /digital-inklusion/pulje-til-frivilligindsatser/projekter-der-har-faaet-tildelt-midler-i-anden-ansoegningsrunde/
HEAD /digital-inklusion/it-frivillig/
HEAD /digital-inklusion/it-frivillig/vejledning-til-digitale-loesninger/
HEAD /digital-inklusion/it-frivillig/vejledning-til-digitale-loesninger/mitid/
HEAD /digital-inklusion/it-frivillig/vejledning-til-digitale-loesninger/digital-post/
HEAD /digital-inklusion/it-frivillig/vejledning-til-digitale-loesninger/nemsms/
HEAD /digital-inklusion/it-frivillig/vejledning-til-digitale-loesninger/digital-fuldmagt/
HEAD /digital-inklusion/it-frivillig/e-laeringskursus/
HEAD /digital-inklusion/it-frivillig/digital-sikkerhed/
HEAD /digital-inklusion/it-frivillig/webinar/
HEAD /digital-inklusion/it-frivillig/hvem-er-de-it-frivillige/
HEAD /digital-inklusion/it-frivillig/nyhedsbrev-for-it-frivillige/
HEAD /digital-inklusion/it-frivillig/support/
HEAD /digital-inklusion/vejledning/
HEAD /digital-inklusion/vejledning/vejledningsmateriale/
HEAD /digital-inklusion/vejledning/vejledningsmateriale/vejledninger/
HEAD /digital-inklusion/vejledning/vejledningsmateriale/vejledninger-paa-tegnsprog/
HEAD /digital-inklusion/vejledning/vejledningsmateriale/fremtidsfuldmagt-en-god-ide/
HEAD /digital-inklusion/vejledning/vejledningsmateriale/find-it-hjaelp-som-borger/
HEAD /digital-inklusion/vejledning/animationsfilm/
HEAD /digital-inklusion/vejledning/animationsfilm/arabisk/
HEAD /digital-inklusion/vejledning/animationsfilm/engelsk/
HEAD /digital-inklusion/vejledning/animationsfilm/farsi/
HEAD /digital-inklusion/vejledning/animationsfilm/russisk/
HEAD /digital-inklusion/vejledning/animationsfilm/ukrainsk/
HEAD /digital-inklusion/vejledning/animationsfilm/somali/
HEAD /digital-inklusion/vejledning/animationsfilm/tyrkisk/
HEAD /digital-inklusion/vejledning/animationsfilm/tegnsprog-dansk/
HEAD /digital-inklusion/nyheder-om-digital-inklusion/
HEAD /digital-inklusion/nyheder-om-digital-inklusion/nyhedsbrev/
HEAD /digital-inklusion/nyheder-om-digital-inklusion/nyhedsarkiv/
HEAD /digital-inklusion/brugeroplevelse/
HEAD /digital-inklusion/brugeroplevelse/metodebank/
HEAD /digital-inklusion/brugeroplevelse/metodebank/vejledning-til-brug-af-metodebanken/
HEAD /digital-inklusion/brugeroplevelse/metodebank/bag-om-metodebanken/
HEAD /digital-inklusion/brugeroplevelse/metodebank/ab-test/
HEAD /digital-inklusion/brugeroplevelse/metodebank/brugerprofiler/
HEAD /digital-inklusion/brugeroplevelse/metodebank/brugerrejser/
HEAD /digital-inklusion/brugeroplevelse/metodebank/deltagerobservation/
HEAD /digital-inklusion/brugeroplevelse/metodebank/desk-research/
HEAD /digital-inklusion/brugeroplevelse/metodebank/dialogvaerktoejer/
HEAD /digital-inklusion/brugeroplevelse/metodebank/fokusgruppe/
HEAD /digital-inklusion/brugeroplevelse/metodebank/guerrillatest/
HEAD /digital-inklusion/brugeroplevelse/metodebank/ideworkshop/
HEAD /digital-inklusion/brugeroplevelse/metodebank/kvalitativt-interview/
HEAD /digital-inklusion/brugeroplevelse/metodebank/moenstergenkendelse/
HEAD /digital-inklusion/brugeroplevelse/metodebank/prototyper/
HEAD /digital-inklusion/brugeroplevelse/metodebank/spoergeskema/
HEAD /digital-inklusion/brugeroplevelse/metodebank/taenke-hoejt-test/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/foer-brugervenlighedstesten/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/foer-brugervenlighedstesten/gevinster/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/foer-brugervenlighedstesten/maalsaetning/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/foer-brugervenlighedstesten/planlaegning/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/under-brugervenlighedstesten/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/under-brugervenlighedstesten/maalgruppe/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/under-brugervenlighedstesten/rekruttering/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/under-brugervenlighedstesten/testopstilling/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/under-brugervenlighedstesten/testopgaver/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/under-brugervenlighedstesten/drejebog/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/under-brugervenlighedstesten/testdata/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/efter-brugervenlighedstesten/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/efter-brugervenlighedstesten/analyse/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/efter-brugervenlighedstesten/risikovurdering/
HEAD /digital-inklusion/brugeroplevelse/brugervenlighedstest/efter-brugervenlighedstesten/afrapportering/
HEAD /digital-inklusion/brugeroplevelse/det-faelles-designsystem/
HEAD /digital-inklusion/brugeroplevelse/ny-i-brugerinddragelse/
HEAD /digital-inklusion/brugeroplevelse/argumenter-for-brugerinddragelse/
HEAD /digital-inklusion/brugeroplevelse/leverandoersamarbejde/
HEAD /digital-inklusion/brugeroplevelse/forankring/
HEAD /digital-inklusion/brugeroplevelse/netvaerk/
HEAD /digital-inklusion/brugeroplevelse/bag-om-guiden/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/flytning/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/bliv-digital-borger/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/skilsmisse/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/miste-paaroerende/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/flytte-til-danmark/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/flytte-til-udlandet/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/blive-pensionist/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/blive-foraelder/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/miste-job-og-faa-nyt-job/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/overblik-over-brugerrejser/starte-uddannelse/
HEAD /digital-inklusion/sammenhaengende-brugerrejser/indsigter-paa-tvaers-af-brugerrejser/
HEAD /digital-inklusion/brugerpanel/
HEAD /digital-transformation/
HEAD /digital-transformation/den-faellesoffentlige-digitaliseringsstrategi/
HEAD /digital-transformation/den-faellesoffentlige-digitaliseringsstrategi/25-aars-faelles-digitaliseringsstrategier/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/hvad-er-digitaliseringsklar-lovgivning/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/hvad-er-digitaliseringsklar-lovgivning/rapporter/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/vejledning/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/vejledning/vejledninger/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/vejledning/eksempler-paa-digitaliseringsklare-lovforslag/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/vejledning/vaerktoejer/
HEAD /digital-transformation/digitaliseringsklar-lovgivning/sekretariatet-for-digitaliseringsklar-lovgivning/
HEAD /digital-transformation/digital-groen-omstilling/
HEAD /digital-transformation/digital-groen-omstilling/groen-databehandling-og-opbevaring/
HEAD /digital-transformation/digital-groen-omstilling/model-for-beregning-af-it-loesningers-klimaaftryk/
HEAD /digital-transformation/digital-europe/
HEAD /digital-transformation/digital-europe/tilskudsfond-for-medfinansiering/
HEAD /digital-transformation/digital-europe/saadan-soeger-du-midler/
HEAD /digital-transformation/smvdigital/
HEAD /digital-transformation/tilliden-til-den-digitale-offentlige-sektor/
HEAD /digital-transformation/tilliden-til-den-digitale-offentlige-sektor/publikationer-om-tillid-til-og-tilfredshed-med-digitale-offentlige-sektor/
HEAD /digital-transformation/tilliden-til-den-digitale-offentlige-sektor/hvorfor-undersoege-borgernes-tillid-til-den-digitale-offentlige-sektor/
HEAD /digital-transformation/tilliden-til-den-digitale-offentlige-sektor/data-om-borgernes-tillid-til-den-digitale-offentlige-sektor/
HEAD /digital-transformation/tilliden-til-den-digitale-offentlige-sektor/data-om-borgernes-tillid-til-den-digitale-offentlige-sektor/metode-for-tillidspublikationerne-2021-2025/
HEAD /digital-transformation/minvirksomhed-lettere-indberetning-til-det-offentlige/
HEAD /digital-transformation/dansk-data-space-forum/
HEAD /digital-transformation/dansk-data-space-forum/tilmelding-til-medlemsforum-for-ddsf/
HEAD /digital-transformation/tilskudspuljen-for-nye-teknologier/
HEAD /tele/
HEAD /tele/bredbaandsudrulning/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/bredbaandskortet/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/ansoegningsprocessen-i-hovedtraek/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/den-almindelige-ordning/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/den-saerlige-ordning/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/kriterier-for-tilskud-pointmodel/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/information-til-kommunerne/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/information-til-bredbaandsudbydere/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/baggrund-og-lovgivning/
HEAD /tele/bredbaandsudrulning/bredbaandspuljen/resultatet-af-bredbaandspuljerne/
HEAD /tele/bredbaandsudrulning/kommunal-stoetteramme/
HEAD /tele/bredbaandsudrulning/bredbaandsdaekning/
HEAD /tele/bredbaandsudrulning/bredbaandsdaekning/bredbaandskortlaegning/
HEAD /tele/bredbaandsudrulning/bredbaandsdaekning/mobilkortlaegning/
HEAD /tele/bredbaandsudrulning/bredbaandsdaekning/tjekditnetdk/
HEAD /tele/bredbaandsudrulning/bredbaandsdaekning/registrer-interesse-for-bedre-bredbaand/
HEAD /tele/bredbaandsudrulning/bredbaandsdaekning/analyser-af-bredbaandsbehov/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/syv-raad-til-kommunerne/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/skabelon-til-en-mastepolitik/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/planklagenaevnets-hensyn-i-mastesager-i-landzone/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/radiotekniske-udtalelser/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/fastsaettelse-af-masteleje/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/guide-til-telemastetyper/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/netvaerksoperatoerernes-underleverandoerer/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/gode-henvisninger-til-mobilstraalinger/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/masteomraadet/lovoverblik-over-etablering-af-master-og-nedgravet-teleinfrastruktur/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/graveomraadet/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/graveomraadet/gravelovens-regler-om-adgang-til-at-grave-paa-privat-ejendom/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/graveomraadet/efteranmeldelse-af-mindre-kortevarende-gravearbejder/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/graveomraadet/graveadgang-og-tomroer/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/graveomraadet/lovoverblik/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/forordningen-om-gigabitinfrastruktur/
HEAD /tele/etablering-af-fysisk-teleinfrastruktur/forordningen-om-gigabitinfrastruktur/vigtige-begreber-i-gia/
HEAD /tele/frekvenser/
HEAD /tele/frekvenser/frekvenstilladelser/
HEAD /tele/frekvenser/frekvenstilladelser/inden-du-anvender-frekvenser/
HEAD /tele/frekvenser/frekvenstilladelser/ansoegning-om-frekvenstilladelse/
HEAD /tele/frekvenser/frekvenstilladelser/generelt-om-tilladelser/
HEAD /tele/frekvenser/frekvenstilladelser/private-net/
HEAD /tele/frekvenser/radioamatoerer/
HEAD /tele/frekvenser/stoej-og-forstyrrelser/
HEAD /tele/frekvenser/stoej-og-forstyrrelser/hvad-kan-du-selv-goere-ved-stoej-og-forstyrrelser/
HEAD /tele/frekvenser/stoej-og-forstyrrelser/forstyrrelse-af-tv/
HEAD /tele/frekvenser/stoej-og-forstyrrelser/forstyrrelse-af-radio/
HEAD /tele/frekvenser/stoej-og-forstyrrelser/forstyrrelse-af-andet-udstyr/
HEAD /tele/frekvenser/stoej-og-forstyrrelser/tilsyn-med-stoej-og-forstyrrelser/
HEAD /tele/frekvenser/stoej-og-forstyrrelser/vindmoeller-kan-forstyrre-radiokaeder/
HEAD /tele/frekvenser/radio-tv-og-traadloese-mikrofoner/
HEAD /tele/frekvenser/maritim-og-aeronautisk-radio/
HEAD /tele/frekvenser/auktioner-og-udbud/
HEAD /tele/internationalt-samarbejde/
HEAD /tele/love-og-regler-paa-teleomraadet/
HEAD /tele/nye-teknologier/
HEAD /tele/nye-teknologier/sekretariatet-for-anvendelse-af-nye-teknologier-sant/
HEAD /tele/nye-teknologier/connecting-europe-facility-cef-2-digital/
HEAD /tele/nye-teknologier/5g/
HEAD /tele/nye-teknologier/5g/fakta-om-5g-og-mobilstraaling/
HEAD /tele/radioudstyr-og-apparater/
HEAD /tele/radioudstyr-og-apparater/radioudstyr/
HEAD /tele/radioudstyr-og-apparater/apparater-og-faste-anlaeg/
HEAD /tele/radioudstyr-og-apparater/apparater-og-faste-anlaeg/apparater/
HEAD /tele/radioudstyr-og-apparater/apparater-og-faste-anlaeg/faste-anlaeg/
HEAD /tele/radioudstyr-og-apparater/harmoniserede-standarder/
HEAD /tele/radioudstyr-og-apparater/markedskontrol/
HEAD /tele/radioudstyr-og-apparater/radiograenseflader/
HEAD /tele/radioudstyr-og-apparater/regler-paa-omraadet/
HEAD /tele/statistik/
HEAD /tele/statistik/telestatistik/
HEAD /tele/statistik/oekonomiske-noegletal-for-telebranchen/
HEAD /tele/statistik/fremskrivning-af-restgruppen/
HEAD /tele/statistik/nordisk-baltisk-telestatistik/
HEAD /tele/telefoni-og-internet/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/mine-rettigheder-som-slutbruger/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/hvordan-klager-jeg/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/mobildaekning/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/brug-af-mobilen-inden-for-eu/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/brug-af-mobilen-inden-for-eu/information-til-borgerne/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/brug-af-mobilen-inden-for-eu/information-til-udbydere/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/brug-af-mobilen-inden-for-eu/tilsyn-med-international-roaming/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/brug-af-mobilen-uden-for-eu/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/brug-af-telefonen-til-udlandet/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/mobiltelefoni-paa-skibe-eller-fly/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/gode-raad-om-udlandstelefoni/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/roaming-telefoni-og-udlandet/telefoni-og-brexit/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/nummerflytning-og-skift-af-bredbaandsudbyder/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/min-mobiltelefon-eller-sim-kort-er-blevet-stjaalet/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/fup-opkald/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/forsyningspligt/
HEAD /tele/telefoni-og-internet/information-til-borgere-og-slutkunder/alarmkommunikation-112/
HEAD /tele/telefoni-og-internet/information-til-udbyderne/
HEAD /tele/telefoni-og-internet/information-til-udbyderne/konkurrenceregulering-paa-teleomraadet/
HEAD /tele/telefoni-og-internet/information-til-udbyderne/netneutralitet/
HEAD /tele/telefoni-og-internet/information-til-udbyderne/tilgaengelighed-for-elektroniske-kommunikationstjenester/
HEAD /tele/telefoni-og-internet/numre/
HEAD /tele/telefoni-og-internet/numre/nummerportering/
HEAD /tele/telefoni-og-internet/numre/den-samlede-danske-nummerplan/
HEAD /tele/telefoni-og-internet/numre/ansoegning-om-numre-og-koder/
HEAD /tele/telefoni-og-internet/numre/nummerafgifter/
HEAD /tele/telefoni-og-internet/numre/nummervejledning/
HEAD /tele/telefoni-og-internet/numre/nummerregistret/
HEAD /tele/telefoni-og-internet/numre/eu-harmoniserede-116-numre/
HEAD /tele/telefoni-og-internet/numre/90-numre/
HEAD /tele/telefoni-og-internet/numre/love-og-bekendtgoerelser-for-numre/
HEAD /tele/telefoni-og-internet/numre/37-serien-til-machine-to-machine-tjenester/
HEAD /tele/telefoni-og-internet/numre/om-sms-koder/
HEAD /tilsyn/
HEAD /tilsyn/ai-forordningen/
HEAD /tilsyn/ai-forordningen/reglerne-i-ai-forordningen/
HEAD /tilsyn/ai-forordningen/reglerne-i-ai-forordningen/definitionen-af-et-ai-system/
HEAD /tilsyn/ai-forordningen/reglerne-i-ai-forordningen/ai-modeller-til-almen-brug/
HEAD /tilsyn/ai-forordningen/reglerne-i-ai-forordningen/ai-faerdigheder/
HEAD /tilsyn/ai-forordningen/reglerne-i-ai-forordningen/hoejrisiko-ai-systemer/
HEAD /tilsyn/ai-forordningen/reglerne-i-ai-forordningen/forbudte-former-for-ai-praksis/
HEAD /tilsyn/ai-forordningen/reglerne-i-ai-forordningen/gennemsigtighedsforpligtelser-for-visse-ai-systemer/
HEAD /tilsyn/ai-forordningen/tilsyn-med-ai-forordningen/
HEAD /tilsyn/ai-forordningen/tilsyn-med-ai-forordningen/henvendelser/
HEAD /tilsyn/ai-forordningen/eu-s-rolle-i-implementeringen/
HEAD /tilsyn/ai-forordningen/eu-s-rolle-i-implementeringen/tilsyn-med-grundlaeggende-rettigheder/
HEAD /tilsyn/ai-forordningen/faq-om-ai-forordningen/
HEAD /tilsyn/ai-forordningen/kommissionens-qa-om-ai-forordningen/
HEAD /tilsyn/ai-forordningen/regulatorisk-sandkasse-for-ai/
HEAD /tilsyn/ai-forordningen/standarder/
HEAD /tilsyn/ai-forordningen/foelgegruppe-for-implementering-af-ai-forordningen/
HEAD /tilsyn/ai-forordningen/konference-om-ai-forordningen/
HEAD /tilsyn/ai-forordningen/konference-om-ai-forordningen/databehandling/
HEAD /tilsyn/dataforordningen/
HEAD /tilsyn/dataforordningen/reglerne-i-dataforordningen/
HEAD /tilsyn/dataforordningen/reglerne-i-dataforordningen/regler-for-forbundne-produkter-og-relaterede-tjenester/
HEAD /tilsyn/dataforordningen/reglerne-i-dataforordningen/regler-for-databehandlingstjenester/
HEAD /tilsyn/dataforordningen/tilsyn-med-dataforordningen/
HEAD /tilsyn/datahoest-bag-skaerme/
HEAD /tilsyn/datastyringsforordningen/
HEAD /tilsyn/digitale-tjenester-dsa/
HEAD /tilsyn/digitale-tjenester-dsa/for-udbydere-regler-for-digitale-tjenester/
HEAD /tilsyn/digitale-tjenester-dsa/for-udbydere-regler-for-digitale-tjenester/forpligtelser-for-digitale-tjenester/
HEAD /tilsyn/digitale-tjenester-dsa/for-udbydere-regler-for-digitale-tjenester/lovgrundlag-for-formidlingstjenester/
HEAD /tilsyn/digitale-tjenester-dsa/paalidelig-indberetter-forsker-eller-tvistbilaegger/
HEAD /tilsyn/digitale-tjenester-dsa/paalidelig-indberetter-forsker-eller-tvistbilaegger/paalidelig-indberetter-af-ulovligt-indhold/
HEAD /tilsyn/digitale-tjenester-dsa/paalidelig-indberetter-forsker-eller-tvistbilaegger/udenretsligt-tvistbilaeggelsesorgan/
HEAD /tilsyn/digitale-tjenester-dsa/paalidelig-indberetter-forsker-eller-tvistbilaegger/forskningsadgang-til-de-stoerste-digitale-tjenester/
HEAD /tilsyn/digitale-tjenester-dsa/saadan-klager-du-over-en-digital-tjeneste/
HEAD /tilsyn/digitale-tjenester-dsa/saadan-klager-du-over-en-digital-tjeneste/dine-rettigheder-over-for-digitale-tjenester/
HEAD /tilsyn/digitale-tjenester-dsa/saadan-klager-du-over-en-digital-tjeneste/naar-du-har-klaget-over-en-digital-tjeneste/
HEAD /tilsyn/digitale-tjenester-dsa/for-myndigheder-paabud-til-digitale-tjenester/
HEAD /tilsyn/digitale-tjenester-dsa/tilsyn-med-digitale-tjenester/
HEAD /tilsyn/digitale-tjenester-dsa/tilsyn-med-digitale-tjenester/dsa-tilsynets-opgaver-og-befoejelser/
HEAD /tilsyn/digitale-tjenester-dsa/tilsyn-med-digitale-tjenester/samarbejde-i-eu-med-koordinatorer-for-digitale-tjenester/
HEAD /tilsyn/digitale-tjenester-dsa/hvad-er-en-digital-tjeneste/
HEAD /tilsyn/domaenenavne/
HEAD /tilsyn/eidas/
HEAD /tilsyn/nis-2/
HEAD /tilsyn/nis-2/hvad-er-nis-2/
HEAD /tilsyn/nis-2/hvad-er-nis-2/nis-2-regelsaet/
HEAD /tilsyn/nis-2/hvad-er-kravene/
HEAD /tilsyn/nis-2/er-i-omfattet-af-nis-2/
HEAD /tilsyn/nis-2/registreringspligt/
HEAD /tilsyn/nis-2/haendelsesunderretning/
HEAD /tilsyn/nis-2/faq-om-nis-2/
HEAD /tilsyn/nis-2/vejledningsmateriale-maalrettet-den-digitale-sektor/
HEAD /tilsyn/nis-2/vejledningsmateriale-maalrettet-den-digitale-sektor/webinarer-og-informationsmoeder/
HEAD /tilsyn/nis-2/vejledningsmateriale-maalrettet-den-digitale-sektor/webinarer-og-informationsmoeder/webinar-om-nis-2/
HEAD /tilsyn/nis-2/vejledningsmateriale-maalrettet-den-digitale-sektor/webinarer-og-informationsmoeder/informationsmoede-om-nis-2-registreringspligt/
HEAD /tilsyn/nis-2/nis-2-registration-of-foreign-entities-in-denmark/
HEAD /tilsyn/nsis/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/hvem-er-omfattet-af-reglerne/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/undgaa-brud-paa-persondatasikkerheden/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/i-tilfaelde-af-brud-paa-persondatasikkerheden/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/hvordan-maa-udbydere-anvende-data/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/vejledninger/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/vejledninger/vejledning-om-a-nummervisning/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/vejledninger/vejledning-om-haandtering-af-brud-paa-persondatasikkerheden/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/vejledninger/vejledning-om-databeskyttelse-i-den-elektroniske-kommunikationssektor/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/vejledninger/vejledning-om-kommunikationshemmeligheden/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/vejledninger/vejledning-om-trafik-og-lokaliseringsdata/
HEAD /tilsyn/persondatasikkerhed-paa-teleomraadet/vejledninger/vejledning-om-risikostyring/
HEAD /tilsyn/sporingsteknologiomraadet/
HEAD /tilsyn/sporingsteknologiomraadet/hvad-er-sporingsteknologier/
HEAD /tilsyn/sporingsteknologiomraadet/hvad-er-sporingsteknologier/sporingsteknologier-pixels-en-kort-guide/
HEAD /tilsyn/sporingsteknologiomraadet/har-du-modtaget-et-hoeringsbrev/
HEAD /tilsyn/sporingsteknologiomraadet/har-du-modtaget-et-hoeringsbrev/tilsynsprocessen/
HEAD /tilsyn/sporingsteknologiomraadet/har-du-modtaget-et-hoeringsbrev/mangler/
HEAD /tilsyn/sporingsteknologiomraadet/har-du-modtaget-et-hoeringsbrev/paabud/
HEAD /tilsyn/sporingsteknologiomraadet/cookievejledningen/
HEAD /tilsyn/sporingsteknologiomraadet/vejledninger-til-offentlige-myndigheder/
HEAD /tilsyn/sporingsteknologiomraadet/vejledninger-til-offentlige-myndigheder/offentlige-myndigheders-brug-af-sporingsteknologi/
HEAD /tilsyn/sporingsteknologiomraadet/vejledninger-til-offentlige-myndigheder/retningslinjer-om-brug-af-sporingsteknologier-paa-offentlige-myndigheders-hjemmesider/
HEAD /tilsyn/sporingsteknologiomraadet/vejledninger-til-offentlige-myndigheder/vejledning-om-brug-af-tredjeparts-sporingsteknologier/
HEAD /tilsyn/sporingsteknologiomraadet/vejledninger-til-tjenesteudbydere/
HEAD /tilsyn/sporingsteknologiomraadet/vejledninger-til-tjenesteudbydere/huskeregler-for-app-udbydere/
HEAD /tilsyn/sporingsteknologiomraadet/vores-tilsyn/
HEAD /tilsyn/webtilgaengelighed/
HEAD /tilsyn/webtilgaengelighed/om-webtilgaengelighed/
HEAD /tilsyn/webtilgaengelighed/om-tilgaengelighedserklaeringen/
HEAD /tilsyn/webtilgaengelighed/vejledning/
HEAD /tilsyn/webtilgaengelighed/vejledning/automatisk-tilgaengelighedstest-med-qualweb/
HEAD /tilsyn/webtilgaengelighed/vejledning/automatisk-tilgaengelighedstest-med-qualweb/enkeltsidetest-med-qualweb-online-evaluator/
HEAD /tilsyn/webtilgaengelighed/vejledning/automatisk-tilgaengelighedstest-med-qualweb/enkeltsidetest-med-qualweb-chrome-browserudvidelse/
HEAD /tilsyn/webtilgaengelighed/vejledning/automatisk-tilgaengelighedstest-med-qualweb/test-flere-sider-med-qualweb-avanceret/
HEAD /tilsyn/webtilgaengelighed/vejledning/automatisk-tilgaengelighedstest-med-qualweb/forstaa-dine-qualweb-resultater/
HEAD /tilsyn/webtilgaengelighed/vejledning/videovejledninger/
HEAD /tilsyn/webtilgaengelighed/vejledning/manuelle-testmetoder/
HEAD /tilsyn/webtilgaengelighed/vejledning/manuelle-testmetoder/tjek-farvekontraster/
HEAD /tilsyn/webtilgaengelighed/vejledning/manuelle-testmetoder/tjek-tastaturtilgaengelighed/
HEAD /tilsyn/webtilgaengelighed/vejledning/manuelle-testmetoder/tjek-struktur-og-layout/
HEAD /tilsyn/webtilgaengelighed/vejledning/manuelle-testmetoder/tjek-semantisk-information/
HEAD /tilsyn/webtilgaengelighed/vejledning/udfyldelse-af-tilgaengelighedserklaering/
HEAD /tilsyn/webtilgaengelighed/vejledning/tilgaengelige-billeder-paa-nettet/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/sidetitel/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/tekstalternativer-til-billeder-alt-tekst/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/kontrastforhold-farvekontrast/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/overskrifter/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/tilpas-stoerrelse-paa-tekst/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/tastaturadgang-og-visuelt-fokus/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/formularer-etiketter-og-fejl/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/indhold-der-bevaeger-sig-blitzer-eller-blinker/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/multimedie-alternativer/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/grundlaeggende-strukturtjek/
HEAD /tilsyn/webtilgaengelighed/vejledning/easy-checks/naeste-skridt/
HEAD /tilsyn/webtilgaengelighed/vejledning/syv-hyppige-fejl-og-deres-betydning/
HEAD /tilsyn/webtilgaengelighed/monitorering-og-tilsyn/
HEAD /tilsyn/webtilgaengelighed/monitorering-og-tilsyn/forenklede-monitoreringer/
HEAD /tilsyn/webtilgaengelighed/monitorering-og-tilsyn/dybdegaaende-monitoreringer/
HEAD /tilsyn/webtilgaengelighed/resultater/
HEAD /tilsyn/webtilgaengelighed/resultater/overordnede-resultater/
HEAD /tilsyn/webtilgaengelighed/resultater/overordnede-resultater/2025/
HEAD /tilsyn/webtilgaengelighed/resultater/overordnede-resultater/2024/
HEAD /tilsyn/webtilgaengelighed/resultater/monitoreringsscorer/
HEAD /tilsyn/webtilgaengelighed/resultater/monitoreringsscorer/2025/
HEAD /tilsyn/webtilgaengelighed/resultater/monitoreringsscorer/2024/
HEAD /tilsyn/webtilgaengelighed/resultater/udestaaende-paabud/
HEAD /tilsyn/webtilgaengelighed/resultater/afrapportering-til-eu-kommissionen/
HEAD /tilsyn/webtilgaengelighed/nyheder-og-netvaerk/
HEAD /tilsyn/webtilgaengelighed/nyheder-og-netvaerk/nyhedsbrev/
HEAD /tilsyn/webtilgaengelighed/nyheder-og-netvaerk/tilmeld-dig-netvaerket/
HEAD /tilsyn/webtilgaengelighed/nyheder-og-netvaerk/tilmeld-dig-netvaerket/netvaerksmoede-om-webtilgaengelighed-i-september/
HEAD /tilsyn/webtilgaengelighed/lovgivning/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/generiske-krav/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/informations-og-kommunikationsteknologi-med-tovejs-talekommunikation/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/informations-og-kommunikationsteknologi-med-mulighed-for-video/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/web/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/dokumenter-ikke-web/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/software/
HEAD /tilsyn/webtilgaengelighed/forstaa-den-tekniske-standard/dokumentation-og-supporttjenester/
HEAD /tilsyn/webtilgaengelighed/spoergsmaal-og-svar-qa/
HEAD /tilsyn/webtilgaengelighed/oplever-du-ikke-tilgaengeligt-indhold/
HEAD /nyheder/nyhedsarkiv/
HEAD /nyheder/nyhedsarkiv/2025/januar/fremtidige-leverandoer-af-nemkonto-systemet-fundet/
HEAD /nyheder/nyhedsarkiv/2025/januar/tre-finalister-til-prisen-for-aarets-digitale-smvomstilling-2025/
HEAD /nyheder/nyhedsarkiv/2025/januar/betaling-for-apps-sikrer-ikke-dine-boerns-private-data/
HEAD /nyheder/nyhedsarkiv/2025/januar/red-barnet-udpeget-som-paalidelig-indberetter/
HEAD /nyheder/nyhedsarkiv/2025/februar/foerste-regler-i-ai-forordningen-traeder-i-kraft/
HEAD /nyheder/nyhedsarkiv/2025/februar/hoej-tilfredshed-blandt-borgerne-med-de-offentlige-digitale-loesninger/
HEAD /nyheder/nyhedsarkiv/2025/februar/historisk-hoej-tilfredshed-med-mitid/
HEAD /nyheder/nyhedsarkiv/2025/marts/danskere-kan-melde-ind-om-daarligt-internet/
HEAD /nyheder/nyhedsarkiv/2025/marts/digitaliseringsstyrelsen-politianmelder-teleselskabet-oister/
HEAD /nyheder/nyhedsarkiv/2025/april/syv-ud-af-ti-virksomheder-er-blevet-mere-effektive-ved-brug-af-ai/
HEAD /nyheder/nyhedsarkiv/2025/april/ny-model-udregner-it-loesningers-klimaaftryk/
HEAD /nyheder/nyhedsarkiv/2025/april/startskud-givet-til-ny-digital-identitetstegnebog/
HEAD /nyheder/nyhedsarkiv/2025/maj/eu-droefter-digitale-investeringer-og-konkurrenceevne-i-aalborg/
HEAD /nyheder/nyhedsarkiv/2025/maj/nu-kan-du-takke-nej-til-et-sundhedskort-af-plastik/
HEAD /nyheder/nyhedsarkiv/2025/juni/evaluering-af-smv-digital/
HEAD /nyheder/nyhedsarkiv/2025/juni/bredbaandspuljen-2025-er-aaben/
HEAD /nyheder/nyhedsarkiv/2025/juni/ny-lov-om-nemkonto/
HEAD /nyheder/nyhedsarkiv/2025/juli/nu-bliver-det-lettere-for-borgerne-at-haandtere-deres-samtykker/
HEAD /nyheder/nyhedsarkiv/2025/juli/i-dag-gaelder-nis2-loven-i-danmark/
HEAD /nyheder/nyhedsarkiv/2025/juli/ny-vicedirektoer-i-digitaliseringsstyrelsen/
HEAD /nyheder/nyhedsarkiv/2025/juli/stadigt-flere-danskere-har-adgang-til-hurtigt-internet/
HEAD /nyheder/nyhedsarkiv/2025/juli/der-er-fulgt-op-paa-kritik-af-digital-post/
HEAD /nyheder/nyhedsarkiv/2025/august/omstillingsprisen-er-aaben-for-indstillinger/
HEAD /nyheder/nyhedsarkiv/2025/august/det-tekniske-er-ofte-ikke-en-barriere-naar-borgerne-moeder-det-offentlige-digitalt/
HEAD /nyheder/nyhedsarkiv/2025/august/saadan-virker-den-digitale-identitetstegnebog/
HEAD /nyheder/nyhedsarkiv/2025/august/oekonomiske-noegletal-for-telebranchen-2024/
HEAD /nyheder/nyhedsarkiv/2025/september/staten-efterlyser-ejerne-af-1-2-mia-kr/
HEAD /nyheder/nyhedsarkiv/2025/september/ai-forordningen-digitaliseringsstyrelsen-udpeget-som-tilsynsmyndighed/
HEAD /nyheder/nyhedsarkiv/2025/september/digital-post-fjerner-links-fra-sms-er/
HEAD /nyheder/nyhedsarkiv/2025/september/dataforordningen-traeder-i-kraft/
HEAD /nyheder/nyhedsarkiv/2025/september/brug-af-ai-er-naesten-tredoblet/
HEAD /nyheder/nyhedsarkiv/2025/oktober/253-adresser-faar-tilskud-til-hurtigere-internet/
HEAD /nyheder/nyhedsarkiv/2025/oktober/vejledning-om-forbudt-ai/
HEAD /nyheder/nyhedsarkiv/2025/november/tilsyn-med-sms-filtre-i-gang/
HEAD /nyheder/nyhedsarkiv/2025/december/ny-fuldmagt-goer-det-nemmere-at-hjaelpe-andre-med-at-holde-overblikket/
HEAD /nyheder/nyhedsarkiv/2025/december/nedbragt-stroemforbrug-paa-digital-post-og-borgerdk/
HEAD /nyheder/nyhedsarkiv/2025/december/open-source-stiller-krav-til-myndighedernes-ansvar-for-it-loesninger/
HEAD /nyheder/nyhedsarkiv/2025/december/boerns-voksenansvarlige/
HEAD /nyheder/nyhedsarkiv/2024/januar/nye-guides-til-ansvarlig-anvendelse-af-generativ-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2024/januar/behandling-af-personoplysninger-i-sundhedskort-appen/
HEAD /nyheder/nyhedsarkiv/2024/januar/fire-organisationer-faar-stoette-til-projekter-for-it-frivillige/
HEAD /nyheder/nyhedsarkiv/2024/januar/nyt-nationalt-koordinationscenter-skal-styrke-cybersikkerhedssektoren/
HEAD /nyheder/nyhedsarkiv/2024/januar/ny-folder-samler-de-bedste-tips-til-at-undgaa-digital-svindel-for-dig-og-dine-naermeste/
HEAD /nyheder/nyhedsarkiv/2024/januar/tre-finalister-fundet-til-omstillingsprisen/
HEAD /nyheder/nyhedsarkiv/2024/januar/danmark-er-i-front-inden-for-offentlig-digitalisering/
HEAD /nyheder/nyhedsarkiv/2024/februar/regeringen-har-indgaaet-aftale-om-en-digitaliseringsstrategi-for-danmark/
HEAD /nyheder/nyhedsarkiv/2024/februar/ny-varslingstjeneste-skal-hjaelpe-virksomheder-med-at-undgaa-cyberangreb/
HEAD /nyheder/nyhedsarkiv/2024/februar/ny-opdatering-goer-det-nemmere-at-aktivere-mitid-app/
HEAD /nyheder/nyhedsarkiv/2024/februar/digitaliseringsstyrelsen-faar-ny-strategi-og-visuel-identitet/
HEAD /nyheder/nyhedsarkiv/2024/februar/nye-principper-skal-hjaelpe-med-inkluderende-digitalisering/
HEAD /nyheder/nyhedsarkiv/2024/februar/tilskudspulje-til-innovative-cybersikkerhedsprojekter-er-nu-aaben/
HEAD /nyheder/nyhedsarkiv/2024/marts/ny-maaling-viser-hoej-tilfredshed-med-blandt-andet-digital-post-mitid-og-borgerdk/
HEAD /nyheder/nyhedsarkiv/2024/marts/ny-regulatorisk-sandkasse-for-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2024/marts/gammel-version-af-mitid-appen-udfases/
HEAD /nyheder/nyhedsarkiv/2024/marts/webinar-bliv-klogere-paa-hvordan-du-ansoeger-om-midler-til-digital-europe-programmet/
HEAD /nyheder/nyhedsarkiv/2024/marts/danskerne-er-tilfredse-med-mitid/
HEAD /nyheder/nyhedsarkiv/2024/marts/ny-analyse-populaere-spil-apps-til-boern-sender-data-videre-til-tech-giganter/
HEAD /nyheder/nyhedsarkiv/2024/april/undgaa-at-blive-klaedt-af-saet-digital-ansvarlighed-paa-bestyrelsens-dagsorden/
HEAD /nyheder/nyhedsarkiv/2024/april/offentlige-myndigheder-skal-forberede-sig-paa-tilslutning-til-nyt-nemkonto-system/
HEAD /nyheder/nyhedsarkiv/2024/april/rollen-som-national-tilsynsmyndighed-med-eu-s-ai-forordning-skal-varetages-af-digitaliseringsstyrelsen/
HEAD /nyheder/nyhedsarkiv/2024/april/digitaliseringsstyrelsen-udgiver-guide-til-borgere-om-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2024/april/soeg-dansk-medfinansiering-til-at-deltage-i-digital-europe-projekter/
HEAD /nyheder/nyhedsarkiv/2024/april/ny-analyse-understreger-vigtigheden-af-fokus-paa-digital-inklusion/
HEAD /nyheder/nyhedsarkiv/2024/april/hoering-af-ny-bekendtgoerelse-for-pulje-til-frivilligindsatser-med-it-hjaelp/
HEAD /nyheder/nyhedsarkiv/2024/april/stor-interesse-for-at-blive-digital-ambassadoer-blandt-borgere-med-minoritetsbaggrund/
HEAD /nyheder/nyhedsarkiv/2024/maj/nye-webinarer-bliv-klogere-paa-om-efteraarets-emner-i-digital-europe-programmet-er-noget-for-dig/
HEAD /nyheder/nyhedsarkiv/2024/maj/danmark-er-nu-medlem-af-alliancen-for-sprogteknologi/
HEAD /nyheder/nyhedsarkiv/2024/maj/pas-paa-snyd-med-festivalbilletter/
HEAD /nyheder/nyhedsarkiv/2024/juni/ny-analyse-af-dataetik-i-store-danske-virksomheder-er-lavet-med-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2024/juni/kom-nemmere-i-maal-med-groenne-it-investeringer/
HEAD /nyheder/nyhedsarkiv/2024/juni/moed-digitaliseringsstyrelsen-paa-folkemoedet-2024/
HEAD /nyheder/nyhedsarkiv/2024/juni/soeg-tilskud-til-jeres-frivillige-arbejde-med-it-hjaelp/
HEAD /nyheder/nyhedsarkiv/2024/juni/mitid-faar-ekstra-antisvindel-mekanisme/
HEAD /nyheder/nyhedsarkiv/2024/juni/digitaliseringsministerens-aarlige-omstillingspris-er-nu-aaben-for-indstillinger/
HEAD /nyheder/nyhedsarkiv/2024/juni/nyt-inspirationskatalog-saadan-bruger-det-offentlige-generativ-ai/
HEAD /nyheder/nyhedsarkiv/2024/juni/nyt-cybersikkerhedsraad-faar-bredere-mandat-til-at-styrke-danmarks-digitale-sikkerhed/
HEAD /nyheder/nyhedsarkiv/2024/juni/smvdigital-har-udbetalt-14-8-millioner-i-brexit-tilskud-til-virksomheders-digitale-omstilling/
HEAD /nyheder/nyhedsarkiv/2024/juni/nu-kan-du-soege-dansk-medfinansiering-til-deltagelse-i-efteraarets-projektindkaldelser-i-digital-europe/
HEAD /nyheder/nyhedsarkiv/2024/juli/revideret-nsis-samt-vejledninger-er-traadt-i-kraft/
HEAD /nyheder/nyhedsarkiv/2024/august/ny-kampagne-flere-kan-faa-gavn-af-digitale-hjaelpemuligheder/
HEAD /nyheder/nyhedsarkiv/2024/august/cybersikkerhedsmaaned/
HEAD /nyheder/nyhedsarkiv/2024/august/danske-hjemmesider-indsamler-data-uden-samtykke/
HEAD /nyheder/nyhedsarkiv/2024/august/tilskudspulje-til-cybersikkerhedsprojekter-for-smv-er-og-start-ups-er-aaben/
HEAD /nyheder/nyhedsarkiv/2024/august/iso-bootcamp-2024-er-aaben-for-tilmeldinger/
HEAD /nyheder/nyhedsarkiv/2024/august/ministerbesoeg-paa-foerste-moede-i-det-nye-cybersikkerhedsraad/
HEAD /nyheder/nyhedsarkiv/2024/august/bliv-klogere-paa-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2024/august/teknisk-fejl-i-nemkontos-selvbetjening-til-borgere/
HEAD /nyheder/nyhedsarkiv/2024/september/kom-med-til-konference-om-digital-inklusion/
HEAD /nyheder/nyhedsarkiv/2024/oktober/danmarks-digitale-offentlige-sektor-er-fortsat-verdens-bedste/
HEAD /nyheder/nyhedsarkiv/2024/oktober/forbrugere-virksomhederne-skal-have-styr-paa-data/
HEAD /nyheder/nyhedsarkiv/2024/oktober/kom-til-lanceringskonference-for-dansk-data-space-forum/
HEAD /nyheder/nyhedsarkiv/2024/oktober/ny-tilskudspulje-skal-styrke-virksomheders-it-sikkerhed-og-dataetik/
HEAD /nyheder/nyhedsarkiv/2024/oktober/udbud-af-den-nationale-eid-gateway/
HEAD /nyheder/nyhedsarkiv/2024/oktober/stor-tillid-til-offentlige-digitale-loesninger/
HEAD /nyheder/nyhedsarkiv/2024/november/mitid-og-nemlog-ins-udviklings-og-driftsleverandoer-faar-ny-ejer/
HEAD /nyheder/nyhedsarkiv/2024/november/nu-kan-borgere-skrive-digital-post-paa-vegne-af-deres-naere/
HEAD /nyheder/nyhedsarkiv/2024/november/faa-stoette-til-digital-omstilling-eller-robotteknologi/
HEAD /nyheder/nyhedsarkiv/2024/november/hvidbog-om-ai/
HEAD /nyheder/nyhedsarkiv/2024/november/seks-organisationer-faar-stoette-til-it-frivillige/
HEAD /nyheder/nyhedsarkiv/2024/december/danske-tekster-goeres-klar-til-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2024/december/danske-boerne-apps-deler-faerre-data-end-udenlandske/
HEAD /nyheder/nyhedsarkiv/2024/december/flere-oeer-faar-nu-hurtig-bredbaandsforbindelse-med-stoette-fra-bredbaandspuljen/
HEAD /nyheder/nyhedsarkiv/2024/december/resultatet-af-bredbaandspuljens-almindelige-ordning-for-2024/
HEAD /nyheder/nyhedsarkiv/2023/januar/frikoeb-af-sikkerhedsstandarden-iso-27002/
HEAD /nyheder/nyhedsarkiv/2023/januar/monitoreringsindsats-har-en-positiv-effekt-for-webtilgaengeligheden-paa-offentlige-hjemmesider/
HEAD /nyheder/nyhedsarkiv/2023/januar/platform-skal-hjaelpe-unge-i-gang-med-at-vaere-digitale-borgere/
HEAD /nyheder/nyhedsarkiv/2023/februar/falske-sms-er-i-omloeb/
HEAD /nyheder/nyhedsarkiv/2023/februar/god-interesse-for-det-kommende-udbud-af-nemkonto/
HEAD /nyheder/nyhedsarkiv/2023/februar/ny-maaling-viser-at-vi-har-taget-mitid-til-os/
HEAD /nyheder/nyhedsarkiv/2023/februar/udrulning-af-mitid-erhverv-runder-en-vigtig-milepael/
HEAD /nyheder/nyhedsarkiv/2023/februar/statusrapport-tager-mellemtid-paa-arbejdet-med-kunstig-intelligens-i-signaturprojekterne-i-kommuner-og-regioner/
HEAD /nyheder/nyhedsarkiv/2023/februar/9-ud-af-10-brugere-er-tilfredse-med-borgerdk/
HEAD /nyheder/nyhedsarkiv/2023/februar/invitation-til-dialogmoede-om-rejsekortdata/
HEAD /nyheder/nyhedsarkiv/2023/februar/nyt-netvaerk-for-myndigheder-saetter-fokus-paa-digital-inklusion/
HEAD /nyheder/nyhedsarkiv/2023/februar/nemid-lukker-snart/
HEAD /nyheder/nyhedsarkiv/2023/februar/tilliden-til-offentlige-digitale-loesninger-er-stabil-efter-et-aar-der-stod-i-nye-digitale-loesningers-tegn/
HEAD /nyheder/nyhedsarkiv/2023/marts/cybersikkerhedsraadet-satte-fokus-paa-it-beredskab-i-staten/
HEAD /nyheder/nyhedsarkiv/2023/marts/kompensationsordning-aendring-i-bek/
HEAD /nyheder/nyhedsarkiv/2023/marts/ny-cyberhotline-skal-oege-borgere-og-virksomheders-digitale-sikkerhed/
HEAD /nyheder/nyhedsarkiv/2023/marts/analyse-om-danskernes-kendskab-til-informationssikkerhed/
HEAD /nyheder/nyhedsarkiv/2023/april/ny-video-maalrettet-offentlige-medarbejdere-og-ledere-saetter-fokus-paa-webtilgaengelighed/
HEAD /nyheder/nyhedsarkiv/2023/april/digitaliserdk-er-nu-klar-med-et-nyt-og-brugervenligt-design/
HEAD /nyheder/nyhedsarkiv/2023/april/videomoeder-mellem-borgere-og-det-offentlige-skaber-vaerdi/
HEAD /nyheder/nyhedsarkiv/2023/april/nyt-vaerktoej-skal-understoette-ansvarlig-brug-af-kunstig-intelligens-i-den-offentlige-sektor/
HEAD /nyheder/nyhedsarkiv/2023/april/nu-kan-unge-finde-vigtig-information-om-forsvarets-dag-paa-mit-overblik/
HEAD /nyheder/nyhedsarkiv/2023/april/overgangen-til-mitid-erhverv-gaar-ind-i-den-afsluttende-fase-30-juni-2023/
HEAD /nyheder/nyhedsarkiv/2023/maj/cybersikkerhedsraadet-droeftede-styrkelse-af-det-offentlig-private-samarbejde/
HEAD /nyheder/nyhedsarkiv/2023/maj/tilmeld-dig-webinar-om-digital-europe-programmets-foerste-ansoegningsrunde-i-2023/
HEAD /nyheder/nyhedsarkiv/2023/maj/ny-lov-om-digital-fritagelse-vedtaget-i-folketinget/
HEAD /nyheder/nyhedsarkiv/2023/maj/vicedirektoer-lars-boenloekke-le-i-radioen/
HEAD /nyheder/nyhedsarkiv/2023/august/national-cybersikkerhedsmaaned-vaer-med-til-at-saette-digital-sikkerhed-paa-dagsordenen/
HEAD /nyheder/nyhedsarkiv/2023/august/iso-bootcamp-2023/
HEAD /nyheder/nyhedsarkiv/2023/august/ny-open-government-partnership-handlingsplan-2023-2025/
HEAD /nyheder/nyhedsarkiv/2023/juni/digitaliseringsstyrelsen-aabner-for-indstillinger-til-prisen-for-aarets-digitale-smvomstilling-2024/
HEAD /nyheder/nyhedsarkiv/2023/juni/opdatering-af-mitid-app-skal-mindske-svindel-og-goere-det-nemmere-at-bruge-mitid-paa-mobilen/
HEAD /nyheder/nyhedsarkiv/2023/juni/nyt-tilsyn-viser-at-indkoebsapps-har-svaert-ved-at-overholde-cookieregler/
HEAD /nyheder/nyhedsarkiv/2023/juni/nye-tekniske-minimumskrav-skal-styrke-it-sikkerheden-i-staten/
HEAD /nyheder/nyhedsarkiv/2023/september/hoering-af-bekendtgoerelse-for-ny-pulje-til-frivilligindsatser-med-it-hjaelp/
HEAD /nyheder/nyhedsarkiv/2023/september/tjenester-fra-tech-giganter-er-udbredt-paa-danske-hjemmesider/
HEAD /nyheder/nyhedsarkiv/2023/september/opdatering-af-sikkerhedsstandarden-iso-27001-og-overgangsperiode-for-statslige-myndigheder/
HEAD /nyheder/nyhedsarkiv/2023/september/digitaliseringsstyrelsens-direktoer-holder-tale-paa-digitaliseringsmessen-2023/
HEAD /nyheder/nyhedsarkiv/2023/september/lars-boenloekke-le-er-ny-vicedirektoer-i-digitaliseringsstyrelsen/
HEAD /nyheder/nyhedsarkiv/2023/september/borgerdk-har-faaet-ny-forside/
HEAD /nyheder/nyhedsarkiv/2023/september/invitation-til-workshop-om-national-3d-model/
HEAD /nyheder/nyhedsarkiv/2023/september/bodil-joergensen-hjaelper-igen-i-aar-danskerne-med-at-undgaa-identitetssvindel/
HEAD /nyheder/nyhedsarkiv/2023/september/nu-starter-cybersikkerhedsmaaneden/
HEAD /nyheder/nyhedsarkiv/2023/oktober/nemkonto-netop-sendt-i-udbud/
HEAD /nyheder/nyhedsarkiv/2023/oktober/soeg-tilskud-til-din-organisations-arbejde-med-it-hjaelp/
HEAD /nyheder/nyhedsarkiv/2023/oktober/nemid-lukker-31-oktober/
HEAD /nyheder/nyhedsarkiv/2023/oktober/ny-opdatering-til-mitid-styrker-sikkerheden-yderligere-og-giver-brugere-bedre-selvbetjeningsmuligheder/
HEAD /nyheder/nyhedsarkiv/2023/oktober/ny-kampagne-skal-hjaelpe-borgere-og-virksomheder-i-kampen-mod-cyberkriminalitet/
HEAD /nyheder/nyhedsarkiv/2023/oktober/i-dag-lukker-nemid/
HEAD /nyheder/nyhedsarkiv/2023/november/digitalisering-oeger-omsaetningen-i-smaa-og-mellemstore-virksomheder/
HEAD /nyheder/nyhedsarkiv/2023/november/digitaliseringsstyrelsen-giver-paabud-til-meta-og-google/
HEAD /nyheder/nyhedsarkiv/2023/november/sikkerheden-hoejnes-i-selvbetjeningen-paa-mitiddk/
HEAD /nyheder/nyhedsarkiv/2023/november/nets-indgaar-aftale-om-salg-af-deres-eid-forretning/
HEAD /nyheder/nyhedsarkiv/2023/november/ny-digitaliseringsstrategi-for-2024-2027/
HEAD /nyheder/nyhedsarkiv/2023/november/faa-et-overblik-over-oekonomiske-ydelser-fra-det-offentlige-et-sted/
HEAD /nyheder/nyhedsarkiv/2023/november/black-friday-undgaa-at-tabe-penge-paa-varer-du-aldrig-modtager/
HEAD /nyheder/nyhedsarkiv/2023/november/kom-og-diskuter-den-digitale-fremtid-paa-dansk-internet-governance-forum-igf-2023/
HEAD /nyheder/nyhedsarkiv/2022/januar/du-kan-nu-logge-paa-udenlandske-selvbetjeningsloesninger-med-dit-nemid/
HEAD /nyheder/nyhedsarkiv/2022/januar/nogle-nemid-brugere-skal-opdatere-id-oplysninger-foer-de-kan-faa-mitid/
HEAD /nyheder/nyhedsarkiv/2022/januar/invitation-til-deltagelse-i-etablering-af-europaeisk-netvaerk-af-test-og-forsoegsfaciliteter-for-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2022/januar/fokus-paa-sammenhaengende-digital-service-11-guider-paa-borgerdk-hjaelper-borgerne-i-afgoerende-livssituationer/
HEAD /nyheder/nyhedsarkiv/2022/januar/nu-igangsaettes-yderligere-tolv-signaturprojekter-med-kunstig-intelligens/
HEAD /nyheder/nyhedsarkiv/2022/januar/hoej-tilfredshed-med-borgerdk/
HEAD /nyheder/nyhedsarkiv/2022/januar/nu-offentliggoeres-den-foerste-eu-rapport-om-tilgaengeligheden-af-offentlige-websteder-og-apps/
HEAD /nyheder/nyhedsarkiv/2022/januar/ny-konference-saetter-fokus-paa-inklusion-af-borgere-der-er-udfordrede-af-den-digitale-hverdag/
HEAD /nyheder/nyhedsarkiv/2022/januar/opdateret-vejledning-skal-hjaelpe-myndigheder-med-at-styrke-it-beredskabet/
HEAD /nyheder/nyhedsarkiv/2022/januar/mitiddk-virker-igen/
HEAD /nyheder/nyhedsarkiv/2022/marts/aarsrapporten-for-digitaliseringsklar-lovgivning-2021/
HEAD /nyheder/nyhedsarkiv/2022/marts/katalog-samfundskritiske-it-systemer/
HEAD /nyheder/nyhedsarkiv/2022/marts/coronapasset-er-nomineret-til-digitaliseringsprisen-2022/
HEAD /nyheder/nyhedsarkiv/2022/marts/danmark-skal-udvikle-ny-vejviser-til-at-rydde-op-i-gamle-love-og-regler/
HEAD /nyheder/nyhedsarkiv/2022/marts/moed-digitaliseringsstyrelsen-paa-offdig-i-aarhus/
HEAD /nyheder/nyhedsarkiv/2022/marts/i-dag-faar-danmark-ny-digital-post-der-styrker-den-offentlige-service-for-baade-borgere-og-virksomheder/
HEAD /nyheder/nyhedsarkiv/2022/marts/coronapas-appen-vinder-sammenhaengsprisen/
HEAD /nyheder/nyhedsarkiv/2022/februar/det-nye-cybersikkerhedsraad-samledes-for-foerste-gang/
HEAD /nyheder/nyhedsarkiv/2022/februar/netvaerk-nytter-bydelsmoedre-og-baba-underviser-borgere-med-etnisk-minoritetsbaggrund-i-mitid/
HEAD /nyheder/nyhedsarkiv/2022/februar/ny-guide-hjaelper-foraeldre-til-at-give-deres-boern-en-sikker-start-paa-det-digitale-liv/
HEAD /nyheder/nyhedsarkiv/2022/februar/en-kort-periode-uden-nye-beskeder-i-offentlig-digital-post/
HEAD /nyheder/nyhedsarkiv/2022/april/ny-rapport-undersoeger-hvordan-offentlige-myndigheder-bedst-kan-stille-groenne-krav-i-deres-indkoeb-af-ydelser-til-databehandling-og-opbevaring/
HEAD /nyheder/nyhedsarkiv/2022/april/hjemmesiden-for-faellesoffentlig-digital-arkitektur-relanceres/
HEAD /nyheder/nyhedsarkiv/2022/maj/markedsdialog-om-drift-udvikling-og-vedligehold-af-borgerdk/
HEAD /nyheder/nyhedsarkiv/2022/maj/regeringen-lancerer-ny-digitaliseringsstrategi/
HEAD /nyheder/nyhedsarkiv/2022/maj/cybersikkerhedsraadet-satte-fokus-paa-borger-og-virksomhedsrettede-initiativer-fra-den-nye-nationale-strategi-for-cyber-og-informationssikkerhed/
HEAD /nyheder/nyhedsarkiv/2022/maj/foerste-statslige-puljeopslag-for-tilskudspulje-for-nye-teknologier-er-nu-aaben/
HEAD /nyheder/nyhedsarkiv/2022/maj/flere-skal-vide-hvor-man-soeger-hjaelp-ved-identitetstyveri/
HEAD /nyheder/nyhedsarkiv/2022/maj/danske-virksomheder-kan-faa-mitid-erhverv-fra-oktober-2022/
HEAD /nyheder/nyhedsarkiv/2022/maj/digitaliseringsstyrelsen-faar-nyt-navn-paa-engelsk-samt-ny-engelsk-hjemmeside/
HEAD /nyheder/nyhedsarkiv/2022/maj/nyhed-om-it-raadets-statusrapport-2021/
HEAD /nyheder/nyhedsarkiv/2022/maj/ekstraordinaer-situation-rykker-sluttidspunktet-for-overgang-til-mitid/
HEAD /nyheder/nyhedsarkiv/2022/juni/undgaa-billetsvindel-ved-sommerens-festivaler-og-koncerter/
HEAD /nyheder/nyhedsarkiv/2022/juni/nye-funktioner-i-mitid-app-goer-det-muligt-at-hjaelpe-paaroerende-med-at-faa-mitid/
HEAD /nyheder/nyhedsarkiv/2022/juni/ny-faellesoffentlig-digitaliseringsstrategi-skal-bidrage-til-at-loese-samfundsudfordringer/
HEAD /nyheder/nyhedsarkiv/2022/juni/ny-digitaliserdk-paa-vej/
HEAD /nyheder/nyhedsarkiv/2022/juni/finansministeren-udpeger-medlemmer-af-statens-it-raad-for-en-ny-periode/
HEAD /nyheder/nyhedsarkiv/2022/juli/borgerdk-i-udbud/
HEAD /nyheder/nyhedsarkiv/2022/juli/digitaliseringsstyrelsen-saetter-cybersikkerhed-paa-dagsordenen-hele-oktober-skal-du-vaere-med/
HEAD /nyheder/nyhedsarkiv/2022/august/opdatering-af-de-20-tekniske-minimumskrav-skal-styrke-it-sikkerhed-hos-de-statslige-myndigheder/
HEAD /nyheder/nyhedsarkiv/2022/august/faellesoffentlig-iso-bootcamp-2022/
HEAD /nyheder/nyhedsarkiv/2022/august/pas-paa-phishing-falske-sms-og-e-mails-om-mitid-i-omloeb/
HEAD /nyheder/nyhedsarkiv/2022/august/nemkonto-svindel-nu-kan-du-soege-om-kompensation/
HEAD /nyheder/nyhedsarkiv/2022/september/moed-digitaliseringsstyrelsen-paa-digitaliseringsmessen-2022/
HEAD /nyheder/nyhedsarkiv/2022/september/to-nye-medlemmer-til-statens-it-raad/
HEAD /nyheder/nyhedsarkiv/2022/september/regeringen-praesenterer-nyt-digitaliseringsraad/
HEAD /nyheder/nyhedsarkiv/2022/september/nu-bliver-mitid-standardvalget-naar-du-skal-logge-paa-offentlige-hjemmesider/
HEAD /nyheder/nyhedsarkiv/2022/september/datavejviserdk-hjaelper-dig-til-at-finde-tilgaengelige-offentlige-data/
HEAD /nyheder/nyhedsarkiv/2022/september/ny-kampagne-giver-danskerne-huskeregel/
HEAD /nyheder/nyhedsarkiv/2022/september/fn-kaarer-endnu-engang-den-danske-digitale-offentlige-sektor-som-verdens-bedste/
HEAD /nyheder/nyhedsarkiv/2022/september/den-nationale-cybersikkerhedsmaaned-er-tilbage/
HEAD /nyheder/nyhedsarkiv/2022/september/vedroerende-medieomtale-af-mulighed-for-hacking-af-mitid/
HEAD /nyheder/nyhedsarkiv/2022/oktober/sluttidspunktet-for-udrulningen-til-mitid-naermer-sig/
HEAD /nyheder/nyhedsarkiv/2022/oktober/ny-faellesoffentlig-iso-bootcamp-2022/
HEAD /nyheder/nyhedsarkiv/2022/oktober/i-dag-lanceres-mitid-erhverv/
HEAD /nyheder/nyhedsarkiv/2022/november/e-mail-og-sms-om-ny-digital-post-faar-nyt-design/
HEAD /nyheder/nyhedsarkiv/2022/november/udbud-af-borgerdk-er-nu-afsluttet/
HEAD /nyheder/nyhedsarkiv/2022/december/kompensation-i-tilfaelde-af-svindel-med-nemkonto-vigtig-frist-i-januar-2023/
HEAD /nyheder/nyhedsarkiv/2021/januar/nyhedsside-med-kontaktboks/
HEAD /nyheder/nyhedsarkiv/2021/januar/nye-tal-nemid-noegleappen-hitter-hos-de-aeldre/
HEAD /nyheder/nyhedsarkiv/2021/januar/danskerne-er-tilfredse-og-trygge-paa-borgerdk/
HEAD /nyheder/nyhedsarkiv/2021/januar/nye-tal-brugerne-af-nemid-er-mere-tilfredse-end-nogensinde-foer/
HEAD /nyheder/nyhedsarkiv/2021/januar/lanceringen-af-det-nye-digital-post-udskydes-i-fire-maaneder/
HEAD /nyheder/nyhedsarkiv/2021/januar/distancearbejde-kraever-oeget-opmaerksomhed-paa-digital-sikkerhed/
HEAD /nyheder/nyhedsarkiv/2021/januar/ny-etisk-guideline-til-udfoerelse-af-digitale-sikkerhedstest/
HEAD /nyheder/nyhedsarkiv/2021/marts/foerste-fase-af-coronapas-lanceret/
HEAD /nyheder/nyhedsarkiv/2021/marts/nu-igangsaettes-indkoeb-af-det-digitale-coronapas/
HEAD /nyheder/nyhedsarkiv/2021/marts/med-valg-af-leverandoerer-rykker-coronapasset-et-stort-skridt-naermere/
HEAD /nyheder/nyhedsarkiv/2021/februar/danmarks-radios-historier-om-identitetstyveri-og-misbrug-af-nemid-er-misvisende-og-skaber-utryghed-paa-fejlagtigt-grundlag/
HEAD /nyheder/nyhedsarkiv/2021/februar/deltag-i-faellesoffentlig-digital-arkitektur-konference-2021/
HEAD /nyheder/nyhedsarkiv/2021/februar/cybersikkerhedsraadet-droeftede-solarwinds-og-den-kommende-nationale-cyber-og-informationssikkerhedsstrategi/
HEAD /nyheder/nyhedsarkiv/2021/april/nu-offentliggoeres-de-foerste-resultater-af-tilsyn-med-overholdelse-af-webtilgaengelighedsloven/
HEAD /nyheder/nyhedsarkiv/2021/april/invitation-til-7-moede-i-netvaerk-for-metode-og-modellering/
HEAD /nyheder/nyhedsarkiv/2021/april/saadan-kommer-coronapas-appen-til-at-se-ud/
HEAD /nyheder/nyhedsarkiv/2021/april/digitaliseringsstyrelsen-kl-og-danske-regioner-opsamler-erfaringer-og-udfordringer-med-kunstig-intelligens-i-det-offentlige/
HEAD /nyheder/nyhedsarkiv/2021/april/it-raadet-goer-status/
HEAD /nyheder/nyhedsarkiv/2021/juni/faa-det-gule-sundhedskort-paa-din-mobil/
HEAD /nyheder/nyhedsarkiv/2021/juni/se-eller-gense-cybersikkerhedsraadets-webinar-om-kompetenceudfordringer/
HEAD /nyheder/nyhedsarkiv/2021/juni/ny-hotline-klar-til-at-hjaelpe-aaret-rundt-i-tilfaelde-af-digitalt-identitetstyveri/
HEAD /nyheder/nyhedsarkiv/2021/juni/oekonomiaftaler-saetter-den-oekonomiske-ramme-for-faellesoffentlig-digitalisering-i-2022-til-2025/
HEAD /nyheder/nyhedsarkiv/2021/juni/et-kort-mindre-og-tre-nomineringer-senere/
HEAD /nyheder/nyhedsarkiv/2021/juni/faellesoffentlige-mini-bootcamps-om-iso-27001/
HEAD /nyheder/nyhedsarkiv/2021/juni/nemlog-in-kan-ikke-benyttes-natten-mellem-den-22-og-23-juni/
HEAD /nyheder/nyhedsarkiv/2021/juni/opdatering-goer-det-nemmere-at-bruge-coronapas-appen/
HEAD /nyheder/nyhedsarkiv/2021/juni/annullering-af-lukkevindue-paa-nemlog-in/
HEAD /nyheder/nyhedsarkiv/2021/juni/cybersikkerhedsraadet-droeftede-cybertruslen-og-kritisk-infrastruktur/
HEAD /nyheder/nyhedsarkiv/2021/juni/analyse-brugerperspektivet-er-centralt-i-arbejdet-med-digital-inklusion/
HEAD /nyheder/nyhedsarkiv/2021/juni/nu-traeder-lov-om-webtilgaengelighed-i-kraft-for-mobilapplikationer/
HEAD /nyheder/nyhedsarkiv/2021/juni/danskernes-opmaerksomhed-paa-digital-sikkerhed-skal-have-et-loeft-den-nationale-cybersikkerhedsmaaned-vender-tilbage/
HEAD /nyheder/nyhedsarkiv/2021/juni/en-million-har-downloadet-sundhedskort-appen/
HEAD /nyheder/nyhedsarkiv/2021/juni/hele-danmarks-nye-digitale-id-er-paa-vej/
HEAD /nyheder/nyhedsarkiv/2021/maj/cybersikkerhedsraadet-inviterer-til-webinar-om-kompetenceudfordringer/
HEAD /nyheder/nyhedsarkiv/2021/maj/testperiode-for-mitid-gaar-i-gang/
HEAD /nyheder/nyhedsarkiv/2021/maj/evaluering-ny-lovgivning-understoetter-i-stigende-grad-god-ansvarlig-digitalisering/
HEAD /nyheder/nyhedsarkiv/2021/maj/invitation-til-teknisk-briefing-om-det-digitale-coronapas/
HEAD /nyheder/nyhedsarkiv/2021/maj/nu-er-det-digitale-coronapas-klar-til-din-smartphone/
HEAD /nyheder/nyhedsarkiv/2021/maj/aendring-af-lov-vil-styrke-adgangen-til-offentlige-data/
HEAD /nyheder/nyhedsarkiv/2021/august/nemlog-in-kan-ikke-benyttes-natten-mellem-den-17-og-18-august/
HEAD /nyheder/nyhedsarkiv/2021/august/overgangen-til-mitid-er-i-gang/
HEAD /nyheder/nyhedsarkiv/2021/august/moed-digitaliseringsstyrelsen-paa-offdig-i-aarhus/
HEAD /nyheder/nyhedsarkiv/2021/august/hotline-ved-identitetstyveri-hjaelper-borgere-doegnet-rundt/
HEAD /nyheder/nyhedsarkiv/2021/august/netcompany-vinder-udbud-af-forvaltning-vedligeholdelse-og-videreudvikling-af-borgerdk/
HEAD /nyheder/nyhedsarkiv/2021/juli/flere-skal-teste-mitid/
HEAD /nyheder/nyhedsarkiv/2021/juli/ny-vejledning-hjaelper-organisationer-i-gang-med-adfaerdsorienteret-cyber-og-informationssikkerhed/
HEAD /nyheder/nyhedsarkiv/2021/oktober/skaerpet-fokus-paa-digital-sikkerhed-den-nationale-cybersikkerhedsmaaned-er-i-gang/
HEAD /nyheder/nyhedsarkiv/2021/oktober/invitation-til-pressemoede-lancering-af-mitid/
HEAD /nyheder/nyhedsarkiv/2021/oktober/fra-i-dag-bliver-nemid-til-mitid/
HEAD /nyheder/nyhedsarkiv/2021/oktober/5-mio-danskere-faar-brev-om-overgangen-til-mitid/
HEAD /nyheder/nyhedsarkiv/2021/oktober/digitaliseringsstyrelsen-inviterer-til-kommentering-af-arkitekturen-bag-mit-overblik/
HEAD /nyheder/nyhedsarkiv/2021/oktober/kom-til-kulturnat-i-digitaliseringsstyrelsen-fredag-den-15-oktober/
HEAD /nyheder/nyhedsarkiv/2021/oktober/der-kan-ikke-sendes-beskeder-i-digital-post-den-26-29-november/
HEAD /nyheder/nyhedsarkiv/2021/oktober/digitaliseringsstyrelsen-klaeder-it-frivillige-paa-til-at-hjaelpe-borgere-med-offentlige-digitale-loesninger/
HEAD /nyheder/nyhedsarkiv/2021/oktober/digitaliseringspartnerskabet-afleverer-sine-anbefalinger-til-regeringen/
HEAD /nyheder/nyhedsarkiv/2021/september/koerekort-appen-har-vundet-digitaliseringsprisen-paa-offdig21/
HEAD /nyheder/nyhedsarkiv/2021/september/algoritmer-paa-arbejde-12-nye-projekter-med-kunstig-intelligens-flytter-ind-paa-raadhuse-og-hospitaler/
HEAD /nyheder/nyhedsarkiv/2021/september/pas-paa-phishing-falske-sms-og-e-mails-i-omloeb/
HEAD /nyheder/nyhedsarkiv/2021/september/cybersikkerhedsraadet-droeftede-europaeiske-tiltag-til-styrket-cybersikkerhed/
HEAD /nyheder/nyhedsarkiv/2021/september/cybersikkerhedsraadet-inviterer-til-webinar-kort-og-konkret-om-cybersikkerhed/
HEAD /nyheder/nyhedsarkiv/2021/september/myndigheder-kan-nu-tilslutte-sig-det-nye-digital-post/
HEAD /nyheder/nyhedsarkiv/2021/september/digitaliseringsstyrelsen-vil-igangsaette-initiativer-som-skal-sikre-bedre-overblik-over-omfanget-af-svindel-som-foelge-af-identitetstyveri/
HEAD /nyheder/nyhedsarkiv/2021/september/moed-digitaliseringsstyrelsen-paa-aarets-digitaliseringsmesse/
HEAD /nyheder/nyhedsarkiv/2021/september/fire-millioner-danskere-bruger-nu-nemid-noegleapp/
HEAD /nyheder/nyhedsarkiv/2021/september/ny-kampagne-hjaelper-danskerne-til-at-blive-kodestaerke/
HEAD /nyheder/nyhedsarkiv/2021/november/mette-lindstroem-lage-ansat-som-ny-vicedirektoer-i-digitaliseringsstyrelsen/
HEAD /nyheder/nyhedsarkiv/2021/november/ny-eu-maaling-danmark-ligger-nummer-et-i-digitalisering-i-eu/
HEAD /nyheder/nyhedsarkiv/2021/november/pas-paa-digitale-svindlere-til-black-friday-og-cyber-monday-2021/
HEAD /nyheder/nyhedsarkiv/2021/november/ny-analyse-afdaekker-borgernes-tillid-til-den-digitale-offentlige-sektor/
HEAD /nyheder/nyhedsarkiv/2021/november/naeste-generation-digital-post-udskydes-til-foerste-kvartal-2022/
HEAD /nyheder/nyhedsarkiv/2021/november/status-for-statens-store-it-projekter/
HEAD /nyheder/nyhedsarkiv/2021/december/hotline-medvirker-til-at-forebygge-identitetstyveri-antallet-af-opkald-er-tredoblet-paa-tre-maaneder/
HEAD /nyheder/nyhedsarkiv/2021/december/aarets-sidste-moede-i-cybersikkerhedsraadet-samlede-op-paa-2021-og-raadets-foerste-periode/
HEAD /nyheder/nyhedsarkiv/2021/december/nu-opdateres-reglerne-om-webtilgaengelighed/
HEAD /nyheder/nyhedsarkiv/2021/december/har-du-faaet-mitid-husk-at-beholde-dit-nemid/
HEAD /nyheder/nyhedsarkiv/2021/december/ny-national-strategi-for-cyber-og-informationssikkerhed-2022-2024/
HEAD /nyheder/nyhedsarkiv/2021/december/fremover-bliver-det-nemmere-for-personer-med-en-fremtidsfuldmagt-eller-generalfuldmagt-at-hjaelpe-med-digital-selvbetjening/
HEAD /nyheder/nyhedsarkiv/2021/december/cybersikkerhedsraadet-skal-nedsaettes-paa-ny-til-perioden-2022-2023/
HEAD /nyheder/nyhedsarkiv/2021/december/det-nye-digital-post-fra-det-offentlige-lanceres-den-21-marts-2022/
HEAD /nyheder/nyhedsarkiv/2020/marts/ny-undersoegelse-danskerne-er-blevet-mere-bevidste-om-digital-sikkerhed/
HEAD /nyheder/nyhedsarkiv/2020/marts/fremgang-i-statens-arbejde-med-informationssikkerhed/
HEAD /nyheder/nyhedsarkiv/2020/marts/ny-undersoegelse-danskerne-er-tilfredse-med-de-digitale-loesninger/
HEAD /nyheder/nyhedsarkiv/2020/marts/statslige-og-faellesoffentlige-loesninger-i-forbindelse-med-covid-19/
HEAD /nyheder/nyhedsarkiv/2020/marts/coronaviruscovid-19-vaerd-at-vide-om-nemid-borgerdk-og-digital-selvbetjening/
HEAD /nyheder/nyhedsarkiv/2020/marts/ny-rapport-ministerierne-har-stoerre-fokus-paa-konsekvenserne-af-ny-lovgivning/
HEAD /nyheder/nyhedsarkiv/2020/marts/udlandsdanskere-boer-installere-nemid-noegleapp/
HEAD /nyheder/nyhedsarkiv/2020/marts/breve-og-digital-post-paa-vej-information-om-coronaviruscovid-19-sendes-nu-direkte-til-alle-danskere/
HEAD /nyheder/nyhedsarkiv/2020/marts/nemid-noegleapp-giver-oeget-beskyttelse-mod-phishing/
HEAD /nyheder/nyhedsarkiv/2020/marts/informationsmoeder-om-det-nye-digital-post-nu-paa-nettet/
HEAD /nyheder/nyhedsarkiv/2020/maj/nyt-advisory-board-skal-raadgive-myndighederne-om-den-kommende-danske-smittestops-app/
HEAD /nyheder/nyhedsarkiv/2020/maj/nye-tal-coronakrisen-goer-os-danskere-mere-digitale/
HEAD /nyheder/nyhedsarkiv/2020/maj/ny-oversigt-saadan-gaar-det-med-den-faellesoffentlige-digitaliseringsstrategi/
HEAD /nyheder/nyhedsarkiv/2020/maj/cybersikkerhedsraadet-droefter-ny-maerkningsordning/
HEAD /nyheder/nyhedsarkiv/2020/maj/kommentering-af-referencearkitektur-for-brugerstyring/
HEAD /nyheder/nyhedsarkiv/2020/maj/ny-vejledning-om-brug-af-geografi-i-lovgivningen/
HEAD /nyheder/nyhedsarkiv/2020/maj/nyt-statsligt-netvaerk-for-informationssikkerhed-skal-fremme-erfaringsudvekslingen-paa-tvaers-af-staten/
HEAD /nyheder/nyhedsarkiv/2020/maj/cybersikkerhedsraadet-holder-webinar-om-tre-vigtige-temaer-for-cyber-og-informationssikkerhed-i-danmark/
HEAD /nyheder/nyhedsarkiv/2020/juni/cybersikkerhed-ny-kampagne-skal-hjaelpe-danskerne-med-at-faerdes-mere-sikkert-paa-nettet/
HEAD /nyheder/nyhedsarkiv/2020/juni/oekonomiaftaler-med-mange-digitale-aftryk/
HEAD /nyheder/nyhedsarkiv/2020/juni/dansk-beskrivelse-af-datasaet-og-datakataloger-er-nu-i-kommentering/
HEAD /nyheder/nyhedsarkiv/2020/juni/ny-digital-arkitektur-skal-sikre-bedre-overblik-for-borgere-og-virksomheder/
HEAD /nyheder/nyhedsarkiv/2020/juni/livlig-debat-til-cybersikkerhedsraadets-webinar/
HEAD /nyheder/nyhedsarkiv/2020/juni/fra-september-2020-skal-alle-offentlige-websteder-vaere-webtilgaengelige/
HEAD /nyheder/nyhedsarkiv/2020/juni/nu-er-appen-smitte-stop-klar-til-danskerne/
HEAD /nyheder/nyhedsarkiv/2020/juni/lancering-af-sprogteknologidk-det-digitale-sprog-i-danmark-skal-vaere-dansk/
HEAD /nyheder/nyhedsarkiv/2020/juni/skaerpet-fokus-paa-cybersikkerhed-den-nationale-cybersikkerhedsmaaned-er-tilbage/
HEAD /nyheder/nyhedsarkiv/2020/august/unge-gaar-glip-af-vigtige-beskeder-fra-det-offentlige-ny-kampagne-skal-hjaelpe-de-unge-godt-i-gang-med-digital-post/
HEAD /nyheder/nyhedsarkiv/2020/august/valg-af-leverandoer-til-monitorering-af-websteders-og-mobilapplikationers-tilgaengelighed/
HEAD /nyheder/nyhedsarkiv/2020/august/nemmere-selvbetjening-med-genbrug-af-data/
HEAD /nyheder/nyhedsarkiv/2020/august/cybersikkerhedsraadet-droefter-bidrag-til-national-strategi-for-cyber-og-informationssikkerhed/
HEAD /nyheder/nyhedsarkiv/2020/august/visma-consulting-as-skal-hjaelpe-digitaliseringsstyrelsen-med-at-udvikle-digitalt-sundhedskort/
HEAD /nyheder/nyhedsarkiv/2020/august/finansministeren-udpeger-medlemmer-af-statens-it-raad-for-en-ny-periode/
HEAD /nyheder/nyhedsarkiv/2020/september/nu-bliver-det-nemmere-for-borgere-med-funktionsnedsaettelse-at-faerdes-paa-offentlige-websteder/
HEAD /nyheder/nyhedsarkiv/2020/september/danmark-fastholder-sin-staerke-position-inden-for-offentlig-digitalisering-i-ny-eu-maaling/
HEAD /nyheder/nyhedsarkiv/2020/september/cybersikkerhedsraadet-inviterer-til-webinar-kort-og-konkret-om-cybersikkerhed/
HEAD /nyheder/nyhedsarkiv/2020/september/13-nye-projekter-skal-bruge-kunstig-intelligens-i-klimakampen-og-til-bedre-behandling-paa-hospitalerne/
HEAD /nyheder/nyhedsarkiv/2020/september/ny-kampagne-skal-ruste-familier-til-at-undgaa-digitale-faelder/
HEAD /nyheder/nyhedsarkiv/2020/september/faellesoffentlig-bootcamp-om-iso-27001/
HEAD /nyheder/nyhedsarkiv/2020/september/nu-bliver-det-nemmere-for-borgerne-at-faa-overblik-over-deres-gaeld-til-det-offentlige/
HEAD /nyheder/nyhedsarkiv/2020/november/iso-bootcamp-boed-i-aar-paa-virtuel-interaktion-og-videndeling/
HEAD /nyheder/nyhedsarkiv/2020/november/markedsdialog-om-udviklingen-af-et-dansksproget-talekorpus/
HEAD /nyheder/nyhedsarkiv/2020/november/digitaliseringsstyrelsens-direktoer-har-faaet-nyt-job/
HEAD /nyheder/nyhedsarkiv/2020/november/danmark-underskriver-charter-med-verdens-foerende-digitale-nationer/
HEAD /nyheder/nyhedsarkiv/2020/november/oktober-satte-fokus-paa-cybersikkerhed/
HEAD /nyheder/nyhedsarkiv/2020/november/digitaliseringsklar-lovgivning-flere-lande-foelger-nu-i-danmarks-fodspor/
HEAD /nyheder/nyhedsarkiv/2020/november/aendret-tidsplan-skubber-lancering-af-ny-erhvervsloesning/
HEAD /nyheder/nyhedsarkiv/2020/november/tag-koerekortet-med-paa-mobilen-koerekort-appen-er-nu-klar-til-brug/
HEAD /nyheder/nyhedsarkiv/2020/november/cybersikkerhedsraadet-gik-i-dybden-med-hovedtemaerne-i-den-kommende-nationale-cyber-og-informationssikkerhedsstrategi/
HEAD /nyheder/nyhedsarkiv/2020/november/undersoegelse-danskerne-er-trygge-ved-at-kommunikere-digitalt-med-det-offentlige/
HEAD /nyheder/nyhedsarkiv/2020/november/vellykket-markedsdialog-om-et-dansksproget-talekorpus/
HEAD /nyheder/nyhedsarkiv/2020/november/softwarerobotter-apps-og-iot-i-referencearkitektur-for-brugerstyring/
HEAD /nyheder/nyhedsarkiv/2020/oktober/den-nationale-cybersikkerhedsmaaned-er-skudt-i-gang/
HEAD /nyheder/nyhedsarkiv/2020/oktober/nu-bliver-det-nemmere-at-skabe-overblik-over-data/
HEAD /nyheder/nyhedsarkiv/2020/oktober/status-for-statens-store-it-projekter/
HEAD /nyheder/nyhedsarkiv/2020/oktober/de-nordisk-baltiske-lande-styrker-samarbejdet-om-den-digitale-og-groenne-omstilling-i-mr-digital/
HEAD /nyheder/nyhedsarkiv/2020/oktober/cybersikkerhedsraadet-har-taget-hul-paa-deres-bidrag-til-kommende-national-cyber-og-informationssikkerhedsstrategi/
HEAD /nyheder/nyhedsarkiv/2020/oktober/danmark-er-blandt-de-bedste-lande-til-offentlig-digitalisering-ifoelge-oecd/
HEAD /nyheder/nyhedsarkiv/2020/oktober/det-offentlige-har-sendt-rekordmange-digitale-meddelelser-under-coronakrisen/
HEAD /nyheder/nyhedsarkiv/2020/oktober/nyt-vaerktoej-kan-teste-it-sikkerheden/
HEAD /nyheder/nyhedsarkiv/2020/oktober/virtuelt-moede-i-netvaerk-for-arkitekturmetode-og-modellering/
HEAD /nyheder/nyhedsarkiv/2020/december/aendring-til-lov-om-digital-post-vedtaget-i-folketinget/
HEAD /nyheder/nyhedsarkiv/2020/december/cybersikkerhedsraadet-gjorde-status-over-det-foerste-aar-og-saa-fremad-mod-2021/
HEAD /nyheder/nyhedsarkiv/2020/december/covid-19-udfordrer-sikkerheden-paa-hjemmearbejdspladserne/
HEAD /nyheder/nyhedsarkiv/2020/december/digitaliseringsstyrelsen-satte-fokus-paa-et-styrket-nordisk-baltisk-samarbejde-om-cyber-og-informationssikkerhed/
HEAD /nyheder/nyhedsarkiv/2020/december/tanja-franck-bliver-ny-direktoer-for-digitaliseringsstyrelsen/
HEAD /nyheder/presse/
HEAD /nyheder/presse/pressebilleder/
HEAD /nyheder/nyhedsbreve/
HEAD /nyheder/nyhedsbreve/udsendte-nyhedsbreve/
HEAD /nyheder/sociale-medier/
HEAD /job/hvem-er-vi/
HEAD /job/karriereveje/
HEAD /job/moed-en-kommende-kollega/
HEAD /job/moed-en-kommende-kollega/tina-windeloev-myrhoej-draminsky/
HEAD /job/moed-en-kommende-kollega/malte-glerup-hockenhull/
HEAD /job/se-hvordan-det-er-at-arbejde-hos-os/
HEAD /job/ledige-stillinger/
HEAD /om-os/om-digitaliseringsstyrelsen/
HEAD /om-os/om-digitaliseringsstyrelsen/strategi-ambition-og-vaerdier/
HEAD /om-os/om-digitaliseringsstyrelsen/maal-og-resultatplan/
HEAD /om-os/om-digitaliseringsstyrelsen/aarsrapport/
HEAD /om-os/om-digitaliseringsstyrelsen/kontakt/
HEAD /om-os/direktionen/
HEAD /om-os/direktionen/tanja-franck/
HEAD /om-os/direktionen/adam-lebech/
HEAD /om-os/direktionen/lars-boenloekke-le/
HEAD /om-os/direktionen/agnes-egsgaard/
HEAD /om-os/organisation/
HEAD /om-os/organisation/direktions-og-kommunikationssekretariat/
HEAD /om-os/organisation/kontor-for-oekonomi-it-styring-og-sikkerhed/
HEAD /om-os/organisation/kontor-for-hr-og-service/
HEAD /om-os/organisation/juridisk-kontor/
HEAD /om-os/organisation/kontor-for-mitid/
HEAD /om-os/organisation/kontor-for-mitid-erhverv-og-digitale-serviceomraader/
HEAD /om-os/organisation/kontor-for-eid-og-apps/
HEAD /om-os/organisation/kontor-for-digital-post/
HEAD /om-os/organisation/kontor-for-nemkonto/
HEAD /om-os/organisation/kontor-for-borgerdk/
HEAD /om-os/organisation/kontor-for-digital-regulering-og-tilsyn/
HEAD /om-os/organisation/kontor-for-ai-analyse-og-inklusion/
HEAD /om-os/organisation/kontor-for-arkitektur-og-teknologi/
HEAD /om-os/organisation/kontor-for-tele/
HEAD /om-os/organisation/borger-og-virksomhedssupport/
HEAD /om-os/internationalt-samarbejde/
HEAD /om-os/internationalt-samarbejde/eu/
HEAD /om-os/internationalt-samarbejde/oecd/
HEAD /om-os/internationalt-samarbejde/besoeg-fra-udlandet/
HEAD /om-os/internationalt-samarbejde/det-nordiske-ministerraad/
HEAD /om-os/internationalt-samarbejde/nordisk-baltisk-samarbejde-om-eu-regler/
HEAD /om-os/offentliggoerelse-af-indkoeb/
HEAD /om-os/love-og-regler/
HEAD /om-os/privatlivspolitik/
HEAD /om-os/whistleblowerordning/
HEAD /om-os/whistleblowerordning/oplysninger-om-vores-behandling-af-dine-personoplysninger/
HEAD /om-os/whistleblowerordning/statistik-vedroerende-whistleblowerordningen-i-digitaliseringsstyrelsen/
HEAD /om-os/om-digstdk/
HEAD /om-os/om-digstdk/cookies/
HEAD /om-os/om-digstdk/aktiv-information/